// Package routes is the shared, curated catalog of the per-verb effective
// CONTRACT that convention-over-configuration web frameworks auto-generate
// for a "resourceful" registration (Rails `resources`, Laravel
// `Route::resource`/`apiResource`, Spring Data REST `@RepositoryRestResource`,
// NestJS `@Crud()`).
//
// Motivation (epic #3829, ticket T10 #3842 — CAP-B)
//
// When a developer writes `resources :widgets` (Rails) or
// `Route::apiResource('posts', PostController::class)` (Laravel), the
// framework synthesizes a FIXED FAMILY of HTTP routes — index / show / create
// / update / destroy (and the form-view new/edit for the non-API variants) —
// each with a well-known DEFAULT STATUS the framework returns (create → 201,
// destroy → 204, index/show/update → 200) without any of it appearing in the
// user's source. grafel already SYNTHESIZES these routes as canonical
// `http:<VERB>:<path>` http_endpoint synthetics (the Rails/Laravel producers),
// but until T10 they carried NO route PROVENANCE and NO per-verb default
// status — so a consumer could not tell a framework-generated route from a
// hand-written one, nor know its contract (the #278 disambiguation, fanned
// across the convention frameworks).
//
// This package is the single source of truth for that contract. It mirrors the
// DRF `effective_contract` shape (#3835): a route synthesized here carries
// `provenance = framework_synthesized`, an `effective_kind`, the action name,
// the verb's `default_status` and its documented `error_statuses` — all curated
// DATA verified against each framework's routing documentation.
//
// QUALITY NOTE: this is curated data. We encode ONLY the statically-recoverable,
// framework-DEFAULT contract. A controller that overrides the status in its body
// is out of scope for the synthesizer (the override lives in code the route
// record already points at via its handler attribution). We never fabricate a
// status: an action with no framework default leaves DefaultStatus == StatusUnknown.
package routes

// Provenance is the route-provenance tag stamped on every route this package
// synthesizes. It is the cross-framework analogue of the DRF `synthesized`
// provenance: the route's existence and contract come from the framework's
// resourceful-routing convention, not from an explicit route declaration the
// reader can see. It deliberately matches across Rails / Laravel / Spring Data
// REST / NestJS Crud so a consumer can filter "framework-generated routes"
// uniformly.
const Provenance = "framework_synthesized"

// EffectiveKind is the per-verb effective-contract kind for a framework-
// synthesized route. The whole resourceful family is generated by the framework
// (no user body), so every member is `synthesized` — the same taxonomy the DRF
// effective-contract pass uses for an unresolved router-default verb (#3835).
const EffectiveKind = "synthesized"

// StatusUnknown is the sentinel DefaultStatus meaning "no curated framework
// default status for this action". Callers MUST NOT treat it as a real HTTP
// status; it signals the action's status is not statically recoverable here.
const StatusUnknown = 0

// VerbContract is the per-action effective contract a resourceful framework
// route carries. It is the route-level analogue of baseknowledge.Member: the
// default success status + documented error statuses + a short behavioural note
// the framework guarantees for the action.
type VerbContract struct {
	// Action is the framework's canonical action name (index / show / create /
	// store / update / destroy / new / edit / getMany / getOne / ...). It is the
	// stable identity a consumer keys the contract on.
	Action string

	// HTTPVerb is the upper-case HTTP method the framework wires the action to
	// ("GET", "POST", "PUT", "PATCH", "DELETE").
	HTTPVerb string

	// DefaultStatus is the default SUCCESS status the framework returns for the
	// action (create/store → 201, destroy → 204, the rest → 200). StatusUnknown
	// (0) means "no curated default — do not fabricate one".
	DefaultStatus int

	// ErrorStatuses lists the documented non-success statuses the action can
	// produce as part of its framework contract (e.g. a 404 on a missing record
	// for show/update/destroy, a 422 on a failed validation for create/update
	// in the frameworks that validate by default). May be empty.
	ErrorStatuses []int

	// Behaviour is a short, human-readable note on the action's framework-default
	// behaviour. Empty when nothing notable is curated.
	Behaviour string

	// DefiningClass is the framework base/facility that DEFINES this synthesized
	// route's existence — the registration facility (Rails `ActionDispatch`
	// resourceful routing, Laravel `ResourceRegistrar`, Spring Data REST
	// `RepositoryRestResource`, NestJS `@nestjsx/crud`). It answers "who
	// generated this route?" the way DRF's defining mixin answers it for an
	// inherited verb. Always set for a curated action.
	DefiningClass string
}

// IsKnown reports whether the contract carries a curated default status.
func (c VerbContract) IsKnown() bool { return c.DefaultStatus != StatusUnknown }
