"""
Django settings for acme_core project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
import logging
from corsheaders.defaults import default_headers
from core.changelog_config import CHANGELOG_MODELS
from core.permissions_config import *
from kombu import Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
env_path = os.path.join(BASE_DIR, ".env")
if os.path.exists(env_path):
    environ.Env.read_env(env_path)

ENVIRONMENT = env("ENVIRONMENT")
API_URL = env("API_BASE_URL_" + ENVIRONMENT, default="http://127.0.0.1:8000")
FRONTEND_BASE = env("FRONTEND_BASE", default="localhost:5173")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
PGCRYPTO_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

REDIS_URL = env("REDIS_URL")

ALLOWED_HOSTS = [
    'core.acme.com',
    'api.core.qa.acme.com',
    'api.core.acme.com',
    env("SERVER_BASE"),
    env("FRONTEND_BASE"),
    "localhost",
    "127.0.0.1",
    env("TESTING_BASE"),
    "acme-core-alb-1219524265.us-east-1.elb.amazonaws.com",
]

# Allow ECS task private IP for ALB health checks
import socket
try:
    ALLOWED_HOSTS.append(socket.gethostbyname(socket.gethostname()))
except Exception:
    pass

AUTH_USER_MODEL = "core.User"

# Application definition

INSTALLED_APPS = [
    "pgcrypto",
    "daphne",
    "django_celery_beat",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "coreapi",
    "core.apps.CoreConfig",  # Update the INSTALLED_APPS setting to point to the CoreConfig class
    "channels",
    "anymail",
    "storages",
    "rest_framework.authtoken", 
    "django_filters"
]

MIDDLEWARE = [
    "core.middleware.performance_debug.PerformanceDebugMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.token_authentication.TokenAuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "core.middleware.logging.LoggingMiddleware",
    "core.middleware.current_user.CurrentUserMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "X-UI-Scope", 
    "X-Group-Id",
]

CORS_ALLOWED_ORIGINS = [
    'http://core.acme.com',
    'https://core.acme.com',
    "https://core.qa.acme.com",
    "http://core.qa.acme.com",
    'http://api.core.acme.com',
    'https://api.core.acme.com',
    "http://" + env("SERVER_BASE"),
    "https://" + env("SERVER_BASE"),
    "http://" + env("FRONTEND_BASE"),
    "https://" + env("FRONTEND_BASE"),
    "http://localhost:8000",
    "https://localhost:8000",
    "http://127.0.0.1:8000",
    "https://127.0.0.1:8000",
    "http://" + env("TESTING_BASE"),
    "https://" + env("TESTING_BASE"),
]
CSRF_TRUSTED_ORIGINS = [
    'http://core.acme.com',
    'https://core.acme.com',
    'http://api.core.acme.com',
    'https://api.core.acme.com',
    "https://core.qa.acme.com",
    "http://core.qa.acme.com",
    "http://18.234.141.44",
    "https://18.234.141.44",
    "http://18.234.141.44:8000",
    "https://18.234.141.44:8000",
    "http://core.acme.com.s3-website-us-east-1.amazonaws.com",
    "https://core.acme.com.s3-website-us-east-1.amazonaws.com",
    "http://acme-core.s3-website-us-east-1.amazonaws.com",
    "https://acme-core.s3-website-us-east-1.amazonaws.com",
]


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

CACHE_MIDDLEWARE_ALIAS = "default"

ROOT_URLCONF = "acme_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DATABASE_NAME"),
        "USER": env("DATABASE_USER"),
        "PASSWORD": env("DATABASE_PASS"),
        "HOST": env("DATABASE_HOST"),
        "PORT": env("DATABASE_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",  # Django Token Authentication
        "django_cognito_jwt.JSONWebTokenAuthentication",  # AWS Cognito JWT Authentication
    ),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": str(BASE_DIR / "acme_core" / "logs" / "logs.log"),
            "level": "INFO",
            "delay": True,
        },
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "simple",
        },
    },
    "formatters": {
        "simple": {
            "format": "%(asctime)s %(name)s %(levelname)s %(message)s",
            "datefmt": "%H:%M:%S",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": True,
        },
        "core": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "botocore": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": False,
        },
        "boto3": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": False,
        },
        "s3transfer": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": False,
        },
        "urllib3": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": False,
        },
        "celery.utils.functional": {
            "handlers": [],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

COGNITO_AWS_REGION = env("COGNITO_AWS_REGION")
COGNITO_USER_POOL = env("COGNITO_USER_POOL")
COGNITO_AUDIENCE = env("COGNITO_AUDIENCE")


# WSGI_APPLICATION = "acme_core.wsgi.application"
ASGI_APPLICATION = "acme_core.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Mailgun add to anymail
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"

ANYMAIL = {
    "MAILGUN_SENDER_DOMAIN": env("MAILGUN_DOMAIN"),
    "MAILGUN_API_KEY": env("MAILGUN_API_KEY"),
}

# Media and static files

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {},
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {},
    },
}

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "media"),
]

AWS_S3_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_S3_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("AWS_BUCKET_NAME")
AWS_S3_REGION_NAME = env("AWS_REGION")
AWS_S3_FILE_OVERWRITE = False


CORS_ALLOW_ALL_ORIGINS = True  # temporary until we isolate and fix the problem
CORS_ORIGIN_ALLOW_ALL = True

# Celery Settings
if ENVIRONMENT == "prod":
    CELERY_TASK_DEFAULT_QUEUE = env("CELERY_TASK_DEFAULT_QUEUE")
    CELERY_TASK_QUEUES = (
        Queue(CELERY_TASK_DEFAULT_QUEUE),
    )
    CELERY_BROKER_URL = "sqs://"
    CELERY_BROKER_TRANSPORT_OPTIONS = {
        "region": env("AWS_REGION"),
        "predefined_queues": {
            CELERY_TASK_DEFAULT_QUEUE: {
                "url": env("CELERY_QUEUE_URL"),
            }
        },
        "visibility_timeout": 3600,
        "wait_time_seconds": 10,
        "polling_interval": 1,
        "use_synchronous_mode": True,
    }

    CELERY_RESULT_BACKEND = f"dynamodb://@{env('AWS_REGION')}/{env('CELERY_DYNAMODB_TABLE_NAME')}?read=1&write=1&ttl_seconds=3600"
    CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
        "create_if_missing": False,  # don't auto-create table
    }

else:
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"  # or your timezone
CELERY_TASK_TRACK_STARTED = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_CHORD_JOIN_TIMEOUT = env.int("CELERY_RESULT_CHORD_JOIN_TIMEOUT", default=600)

# For django-celery-beat
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

ECB_PDF_PIPELINE_ENABLED = env.bool("ECB_PDF_PIPELINE_ENABLED", default=False)
ECB_PDF_QUEUE_URL = env("ECB_PDF_QUEUE_URL", default="")
ECB_OCR_DEBUG_PAYLOADS = env.bool("ECB_OCR_DEBUG_PAYLOADS", default=False)
ECB_OCR_WRITE_TO_CONTROLLER_DB = env.bool("ECB_OCR_WRITE_TO_CONTROLLER_DB", default=False)

MONGO_DB_USER = env("MONGO_DB_USER")
MONGO_DB_PASSWORD = env("MONGO_DB_PASSWORD")
MONGO_DB_HOST = env("MONGO_DB_HOST")
MONGO_DB_NAME = env("MONGO_DB_NAME")

FILE_UPLOAD_MAX_MEMORY_SIZE = 250 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 250 * 1024 * 1024

DOBSYNC_SETTINGS = {
        "DOB.BATCH_SIZE": 100, 
        "CORE.NUM_WORKERS": 1, 
        "DOB.INSPECTION_DATE_FORMAT": "%m/%d/%Y", 
        "DOB.INSPECTION_TYPES_MAPPING": {
            "1": "ONE_YEAR",
            "7": "PERIODIC",
            "3": "FIVE_YEARS",
        }, 
        "DOB.DATAFRAME_COLUMNS": [
            "BIN",
            "Location",
            "GroupGuid",      
            "DeviceID",
            "FiledDate",
            "ELV29Guid",
            "ELV3Guid",
            "InspectionTypeID",
            "OwnerLegalStatement", 
            "PerformingInspectorEmail",
            "PerformingAgencyInspector",
            "PerformingMaintenanceDirectorEmail",
            "PerformingAgencyDirectorCoDirector",
            "PerformaingDirectorEmail",
            "PerformingAgencyDirectorStatement",
            "PerformingAgencyInspectorStatement",
            "WitnessingAgencyInspector",
            "WitnessingAgencyInspectorEmail",
            "WitnessingAgencyDirectorEmail",
            "WitnessingAgencyDirectorStatement", 
            "WitnessingAgencyInspectorStatement",
            "WitnessingAgencyDirectorCoDirector",
            "DefectsExists",
            "InspectionDate",
            "TrackingNumber",
            "ComplianceReportStatusId",
            "ComplianceReportStatus",
            "ModifiedDate"
        ],
        "CORE.CHECKLIST_TYPES_MAPPING": {
            "ONE_YEAR": 1,
            "PERIODIC": 3,
            "FIVE_YEAR": 2,
        },
        "CORE.DEFICIENCY_MAPPING": {
            "ELV3DefectGuid": "id",
            "ElevatorPart": "part",
            "SuggestedRemedy": "remedy",
            "ViolationCondition": "condition",
            "Comments": "comment",
            "DefectStatus": "status"
        }
}



if(ENVIRONMENT == "prod"):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    #SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_CONTENT_TYPE_NOSNIFF = False

    SECURE_CROSS_ORIGIN_OPENER_POLICY = (
        None
    )

# CELERY_TASK_ALWAYS_EAGER = True
# CELERY_TASK_EAGER_PROPAGATES = True
