// Auto-generated by tygo from internal/types/kinds.go — do not hand-edit entity/relationship kinds.
// All other types are hand-maintained against the JSON shapes returned by REST handlers.

// ────────────────────────────────────────────────────────────────────────────
// Enumerations (from internal/types/kinds.go)
// ────────────────────────────────────────────────────────────────────────────

export type EntityKind =
  | 'Operation' | 'Component' | 'Class' | 'Function'
  | 'Schema' | 'Variable' | 'Reference' | 'Pattern'
  | 'Evolution' | 'Endpoint' | 'Route' | 'Service'
  | 'View' | 'UIComponent' | 'JSX' | 'Stylesheet'
  | 'Queue' | 'Event' | 'Datastore' | 'DataAccess'
  | 'ExternalAPI' | 'InfraResource' | 'CodeBlock'
  | 'Document' | 'Heading' | 'ScopeUnknown'
  | 'External' | 'Project' | 'Config' | 'Model'
  | 'AgentPattern' | 'MessageTopic' | 'Process'

export type RelationshipKind =
  | 'CALLS' | 'IMPORTS' | 'EXTENDS' | 'IMPLEMENTS'
  | 'USES' | 'USES_HOOK' | 'CONTAINS' | 'DEPENDS_ON'
  | 'REFERENCES' | 'ROUTES_TO' | 'SERVES' | 'PUBLISHES_TO'
  | 'TESTS' | 'HAS_PROPS' | 'ACCESSES_TABLE' | 'INJECTED_INTO'
  | 'READS_FROM' | 'WRITES_TO' | 'RENDERS' | 'RETURNS'
  | 'TAGGED_AS'
  | 'EXEMPLAR' | 'TOUCHES' | 'ANTI_EXEMPLAR' | 'SUPERSEDES'
  | 'CONFLICTS_WITH' | 'CO_APPLIES_WITH' | 'PREREQUISITE' | 'CREATED_BY'
  | 'PLATFORM_VARIANT_OF' | 'QUERIES' | 'FETCHES'
  | 'SUBSCRIBES_TO' | 'TRANSFORMS'
  | 'WS_SUBSCRIBES_TO' | 'WS_EMITS' | 'WS_CONNECTS'
  | 'STREAMS_FROM' | 'STREAMS_TO'
  | 'GRAPHQL_SUBSCRIBES' | 'GRAPHQL_PUBLISHES'
  | 'STEP_IN_PROCESS' | 'ENTRY_POINT_OF'
  /** Synthetic edge between community centroids (zoom-out tier only). */
  | 'COMMUNITY_LINK'

export type HttpVerb = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS' | 'ANY' | 'WS'

// ────────────────────────────────────────────────────────────────────────────
// Core wire types (from internal/mcp/tools.go — serializeEntity)
// ────────────────────────────────────────────────────────────────────────────

export interface Finding {
  question: string
  answer: string
  type: string
  nodes?: string[]
  saved_at: string
}

export interface Entity {
  id: string
  label: string
  qualified_name: string
  kind: EntityKind
  source_file: string
  start_line: number
  end_line: number
  language: string
  repo: string
  pagerank?: number
  community_id?: number
  properties?: Record<string, unknown>
  findings?: Finding[]
}

export interface Relationship {
  from_id: string
  to_id: string
  kind: RelationshipKind
  cross_repo?: boolean
  target_repo?: string
  link_method?: 'http' | 'kafka_topic' | 'ws_channel'
  properties?: Record<string, unknown>
}

// ────────────────────────────────────────────────────────────────────────────
// Registry & groups (GET /api/registry, GET /api/dashboard/init)
// ────────────────────────────────────────────────────────────────────────────

export interface RepoMeta {
  slug: string
  display_name: string
  language: string
  entity_count: number
  indexed_at?: string
}

export interface GroupMeta {
  id: string
  display_name: string
  repos: RepoMeta[]
  entity_count: number
  indexed_at?: string
  /** Unresolved edges percentage for the group (0–100). Percentage of graph edges that point to unknown or ambiguous targets. Present when the group has been indexed. */
  bug_rate?: number
  /** Rolling unresolved edges history (oldest → newest), used for the sparkline. */
  bug_rate_history?: number[]
  /** Top frameworks detected across all repos in the group (sorted by usage, capped at 8). */
  frameworks?: string[]
}

export interface Registry {
  groups: GroupMeta[]
  version: string
}

// ────────────────────────────────────────────────────────────────────────────
// Graph thumbnail / layout-snapshot (#983)
// GET /api/graph/{group}/layout-snapshot
// ────────────────────────────────────────────────────────────────────────────

/** Single node in the layout-snapshot response. Positions are normalised [0,1]. */
export interface ThumbnailNode {
  /** Prefixed entity ID (repo:hash) */
  id: string
  /** Repo slug — used for per-repo colour fallback when community_id absent */
  repo: string
  /** Community cluster id — drives fill colour */
  c?: number
  /** Normalised x position [0,1] */
  x: number
  /** Normalised y position [0,1] */
  y: number
  /** Total degree (in+out) — drives dot radius */
  d: number
}

export interface GraphThumbnailResponse {
  nodes: ThumbnailNode[]
  total_nodes: number
}

export interface DashboardInitResponse {
  registry: Registry
  groups: GroupMeta[]
  settings: Record<string, unknown>
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 4 — API & Contracts Explorer (GET /api/paths/{group})
// ────────────────────────────────────────────────────────────────────────────

export interface HttpEndpoint {
  id: string
  repo: string
  verb: HttpVerb
  path: string
  handler: string
  framework?: string
  response_keys?: string[]
  dynamic_response?: boolean
  is_webhook?: boolean
  webhook_provider?: string
  status_codes?: number[]
  inbound_fetches?: string[]
  outbound_queries?: string[]
  language?: string
}

/** A single row in the path list — groups all verbs + endpoints for one unique path string */
export interface PathRow {
  path: string
  path_hash: string
  verbs: HttpVerb[]
  endpoints: HttpEndpoint[]
  multiplicity: number           // total endpoint count for this path (incl. ViewSet expansion)
  repos: string[]                // which repos define handlers for this path
  frameworks: string[]
  is_webhook: boolean
  webhook_provider?: string
  /** Owning controller class / module / router-prefix group (from extractor).
   *  Used for grouped view in Surface 4. */
  controller?: string
}

/** Prefix tree node for the sidebar */
export interface PathTreeNode {
  prefix: string                 // e.g. "/api/v1/"
  label: string                  // display label e.g. "v1"
  count: number                  // total paths under this prefix
  children: PathTreeNode[]
}

/** One backend service in the grouped-by-owning_backend response (#1218/#1219). */
export interface BackendInfo {
  /** Canonical backend slug / repo name, e.g. "api-service" */
  name: string
  /** Human-readable service type, e.g. "REST", "gRPC", "GraphQL" */
  service_type?: string
  /** Number of endpoint definitions owned by this backend */
  count: number
  /** Paths owned by this backend (populated by Sub-B #1218) */
  paths: PathRow[]
  /**
   * ANY-rate for this backend — fraction of FETCH edges whose method resolves
   * to ANY (post-#1126 method resolution). Range [0, 1].
   * Present when the backend analysis has run; absent otherwise.
   */
  any_rate?: number
  /**
   * True when at least one endpoint in another backend's repo calls a path
   * defined in this backend.
   */
  has_cross_backend_refs?: boolean
}

export interface PathListResponse {
  paths: PathRow[]
  tree: PathTreeNode[]
  total: number
  /**
   * Backend-grouped response from Sub-B (#1218).
   * Present when the backend has been rebuilt with the grouped handler.
   * Absent (undefined) in older backends — fall back to flat `paths[]`.
   */
  backends?: BackendInfo[]
}

// ── Orphan Callers — frontend FETCH call sites with no backend handler match ──

/** Reason why a call site has no matching backend handler */
export type OrphanCallerReason =
  | 'dynamic_baseurl'
  | 'template_literal'
  | 'no_handler_found'

export interface OrphanCaller {
  id: string
  /** source file containing the FETCH call site */
  caller_file: string
  /** line number of the call site */
  caller_line: number
  /** URL pattern (may contain placeholders like {id} or ${var}) */
  url_pattern: string
  /** HTTP method */
  method: string
  /** Why this caller has no matching backend handler */
  reason: OrphanCallerReason
  /** Human-readable description of the resolution suggestion */
  repair_hint?: string
}

export interface OrphanCallersResponse {
  callers: OrphanCaller[]
  total: number
}

export interface PathFilters {
  prefix?: string
  q?: string
  repo?: string
  framework?: string
  status_code?: number
  is_webhook?: boolean
}

/** Full detail for one path — GET /api/paths/{group}/{pathHash} */
export interface HandlerDetail {
  entity: Entity
  verb: HttpVerb
  framework?: string
  source_file: string
  start_line: number
  language: string
  /** True when docgen has run and produced a summary for this handler */
  has_docs?: boolean
  /** AI-generated summary from /generate-docs */
  docs_summary?: string
  /** Path to the generated docs file */
  docs_path?: string
}

export interface ResponseShape {
  verb: HttpVerb
  keys: string[]
  dynamic: boolean
  status_codes: number[]
}

export interface PathDetailResponse {
  path: string
  path_hash: string
  verbs: HttpVerb[]
  handlers: HandlerDetail[]
  response_shapes: ResponseShape[]
  inbound_fetches: Entity[]      // entities that FETCHES this path
  outbound_queries: Entity[]     // entities that QUERIES db from handler
  is_webhook: boolean
  webhook_provider?: string
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 2 — Process Flow Explorer
// ────────────────────────────────────────────────────────────────────────────

export interface ProcessStep {
  entity_id: string
  label: string
  source_file: string
  start_line: number
  repo: string
  step_index: number
  edge_kind: RelationshipKind
  /** #1147 step-kind annotation — e.g. 'http_fetch', 'db_query', 'message_publish' */
  step_kind?: string
  /** #1147 observed side-effects for this step */
  side_effects?: string[]
}

export type FlowEntryKind =
  | 'http_handler'
  | 'message_consumer'
  | 'scheduled_task'
  | 'component_render'
  | 'test'
  | 'cli_command'
  | 'function'
  | 'internal'

export type FlowPriorityHint = 'high' | 'medium' | 'low'

/** AI-generated enrichment frontmatter for a process_flow entity (#1152). */
export interface FlowEnrichment {
  entity_id?: string
  kind?: string
  summary?: string
  preconditions?: string
  expected_outcome?: string
  steps?: string[]
  gaps?: string[]
  group?: string
  group_label?: string
  rank?: number
  disqualified?: boolean
}

/** Which enrichment fields are populated for a flow (#1152). */
export interface EnrichmentHealth {
  summary: boolean
  preconditions: boolean
  expected_outcome: boolean
  steps: boolean
  gaps: boolean
}

export interface Process {
  process_id: string
  repo: string
  label: string
  entry_id: string
  entry_name: string
  entry_kind?: EntityKind
  terminal_id: string
  step_count: number
  cross_stack: boolean
  crosses_external_lib?: boolean
  terminal_is_phantom?: boolean
  chain_labels: string[]
  source_file?: string
  /** Populated on action=get (detail); absent on action=list */
  steps?: ProcessStep[]
  /** entity_kind of the process entry point (http, kafka_consumer, scheduled, ws_handler) */
  entity_kind?: 'http' | 'kafka_consumer' | 'scheduled' | 'ws_handler'
  /** #1147 annotations */
  flow_side_effects?: string[]
  is_cross_repo?: boolean
  /** #1148 — new per-process fields from Flows v2 backend */
  flow_entry_kind?: FlowEntryKind
  entry_module?: string
  priority_hint?: FlowPriorityHint
  dominant_step_kind?: RelationshipKind | null
  complexity_score?: number
  /** #1105 unified enrichment — preconditions / expected_outcome / ai_summary */
  enrichment?: {
    ai_summary?: string
    preconditions?: string[]
    expected_outcome?: string
    writes_db_table?: string[]
    publishes_to?: string[]
    external_calls?: string[]
    read_sources?: string[]
    write_sinks?: string[]
    linked_endpoint_id?: string
    linked_topic_id?: string
  }
  /** #1152 enrichment fields */
  docs_summary?: string
  docgen_status?: 'enriched' | 'pending' | 'stale'
  enrichment_health?: EnrichmentHealth
}

/** Summary entry in the top-level entry_kind_groups array (#1148) */
export interface FlowEntryKindGroup {
  kind: FlowEntryKind
  count: number
}

// ── Dead-ends (#1145) ─────────────────────────────────────────────────────────

export type DeadEndReason =
  | 'no_useful_sink'
  | 'single_step'
  | 'unresolved_callee'
  | 'phantom_terminal'
  | 'dead_end'

export interface FlowDeadEnd {
  process_id: string
  entry_name: string
  entry_id: string
  entry_kind?: 'http' | 'kafka_consumer' | 'scheduled' | 'ws_handler'
  repo: string
  step_count: number
  reason: DeadEndReason
}

export interface FlowDeadEndsResponse {
  dead_ends: FlowDeadEnd[]
  total: number
}

// ── Truncated flows (#1146) ───────────────────────────────────────────────────

export type TruncatedReason =
  | 'unresolved_callee'
  | 'cycle_detected'
  | 'depth_exceeded'
  | 'external_boundary'
  | 'truncated'

export type TruncatedSeverity = 'info' | 'warn' | 'error'

export interface FlowTruncated {
  process_id: string
  entry_name: string
  entry_id: string
  entry_kind?: 'http' | 'kafka_consumer' | 'scheduled' | 'ws_handler'
  repo: string
  step_count: number
  truncation_step: number
  reason: TruncatedReason
  severity: TruncatedSeverity
}

export interface FlowTruncatedResponse {
  truncated: FlowTruncated[]
  total: number
}

export interface FlowListResponse {
  processes: Process[]
  total: number
  has_more: boolean
  /** Present when the backend has classified processes by entry_kind (#1148) */
  entry_kind_groups?: FlowEntryKindGroup[]
}

export interface FlowDetailResponse {
  process: Process
  chain_entities: Entity[]
  source_snippets: Record<string, string>
}

/** Response shape for POST /api/flows/{group}/{processId}/trigger-enrichment */
export interface TriggerEnrichmentResponse {
  status: 'queued'
  message: string
  process_id: string
  group: string
}

export interface FlowFilters {
  entry?: string
  cross_stack_only?: boolean
  limit?: number
  repo?: string
}

export interface SwimLaneEntry {
  repo: string
  steps: ProcessStep[]
  laneIndex: number
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 3 — Broker Topology
// ────────────────────────────────────────────────────────────────────────────

export type BrokerProtocol = 'kafka' | 'rabbitmq' | 'sqs' | 'pubsub' | 'nats' | 'redis' | 'redis-stream' | 'task-queue'
export type ChannelProtocol = 'websocket' | 'sse' | 'graphql_subscription' | 'redis_pubsub'
export type ServerlessProtocol = 'serverless'
export type TopologyProtocol = BrokerProtocol | ChannelProtocol | ServerlessProtocol

/** A lightweight entity stub carried in topology responses (avoids re-fetching full Entity) */
export interface TopologyEntityStub {
  id: string
  label: string
  repo: string
  kind: EntityKind
  source_file: string
  start_line: number
}

export interface TopicNode {
  id: string
  repo: string
  label: string
  broker: BrokerProtocol
  producer_ids: string[]
  consumer_ids: string[]
  transforms_to: string[]
}

export interface QueueNode {
  id: string
  repo: string
  label: string
  broker: BrokerProtocol
  /** framework property from async task extractors (celery/dramatiq/rq/sidekiq/bull) — #1116 */
  framework?: string
  /** scheduled=true for SCOPE.ScheduledJob entities (celery_beat, APScheduler, node-cron, etc.) — #1116 */
  scheduled?: boolean
  /** cron/interval expression when scheduled=true — #1116 */
  schedule?: string
  queue_type?: 'direct' | 'fanout' | 'standard' | 'fifo' | 'subscription'
  producer_ids: string[]
  consumer_ids: string[]
}

export interface NatsSubject {
  id: string
  repo: string
  label: string
  broker: 'nats'
  producer_ids: string[]
  consumer_ids: string[]
}

export interface ChannelNode {
  id: string
  repo: string
  label: string
  channel_type: ChannelProtocol
  server_endpoint?: string
  emitter_ids: string[]
  subscriber_ids: string[]
}

export interface GraphQLSubscription {
  id: string
  repo: string
  label: string
  schema_type: string
  return_type?: string
  publisher_ids: string[]
  subscriber_ids: string[]
}

export interface TopologyTransform {
  from_id: string
  to_id: string
  transformer_id: string
  repo: string
}

/** A serverless function node — AWS Lambda, GCP Cloud Functions, Azure Functions */
export interface FunctionNode {
  id: string
  repo: string
  label: string
  /** Cloud provider: 'aws-lambda' | 'gcp-cloudfunction' | 'azure-function' | 'serverless' */
  provider: string
  /** Entities that invoke (CALLS) this function */
  invoker_ids: string[]
  /** Entities that handle (HANDLES) this function */
  handler_ids: string[]
}

/** Broker-level grouping metadata — populated by backend when #1139 lands.
 *  The frontend derives the same structure client-side when this is absent.  */
export interface BrokerServiceGroup {
  /** Broker display name e.g. "RabbitMQ" */
  broker: string
  /** Machine-safe broker slug e.g. "rabbitmq" */
  broker_slug: TopologyProtocol
  /** Topic / queue / channel IDs belonging to this broker */
  topic_ids: string[]
  /** Per-service breakdown within this broker */
  services: Array<{
    service: string
    topic_ids: string[]
  }>
  /** Count of topics with zero consumers (orphan publishers) */
  orphan_publisher_count: number
  /** Count of topics with zero producers (orphan subscribers) */
  orphan_subscriber_count: number
}

export interface TopologyResponse {
  topics: TopicNode[]
  queues: QueueNode[]
  channels: ChannelNode[]
  /** Serverless functions (#946) */
  functions: FunctionNode[]
  graphql_subscriptions: GraphQLSubscription[]
  nats_subjects: NatsSubject[]
  transforms: TopologyTransform[]
  producers: Record<string, TopologyEntityStub>
  consumers: Record<string, TopologyEntityStub>
  /** Broker / service grouping metadata (#1139). May be absent in older backends — derive client-side when missing. */
  broker_groups?: BrokerServiceGroup[]
}

export interface TopologyFilters {
  protocols?: TopologyProtocol[]
  topic?: string
}

// ── Orphan Publishers / Subscribers (#1136, #1137) ───────────────────────────

export type OrphanReason = 'no_consumer' | 'no_producer' | 'no_handler'

export interface OrphanPublisher {
  id: string
  topic_id: string
  topic_label: string
  broker: string
  service: string
  producer_count: number
  reason: OrphanReason
  /** File path of the publish call site */
  file?: string
  /** Line number of the publish call site */
  line?: number
}

export interface OrphanSubscriber {
  id: string
  topic_id: string
  topic_label: string
  broker: string
  service: string
  consumer_count: number
  reason: OrphanReason
  /** File path of the consume call site */
  file?: string
  /** Line number of the consume call site */
  line?: number
}

export interface OrphanPublishersResponse {
  publishers: OrphanPublisher[]
  total: number
}

export interface OrphanSubscribersResponse {
  subscribers: OrphanSubscriber[]
  total: number
}

// ── Per-topic detail — GET /api/topology/{group}/topics/{topicId} (#1138) ───

export type LifecycleState = 'active' | 'orphan_publisher' | 'orphan_subscriber' | 'orphan'

export interface TopicDetailEntityStub {
  entity_id: string
  name: string
  source_file: string
  start_line: number
  repo: string
}

export interface TopicDetailV2 {
  id: string
  label: string
  broker: string
  framework?: string
  scheduled?: boolean
  schedule?: string
  message_schema?: string | null
  lifecycle_state: LifecycleState
  flow_count: number
  cross_repo: boolean
  producers: TopicDetailEntityStub[]
  consumers: TopicDetailEntityStub[]
  related_topics: Array<{ id: string; label: string; broker: string }>
  usage_history: Array<{ date: string; count: number }>
  docs_summary?: string | null
  enrichment?: {
    gaps?: string[]
    volume_estimate?: string
    typical_payload_size_bytes?: number
  } | null
  /** ISO timestamp of last index rebuild */
  last_rebuilt?: string | null
}

// ────────────────────────────────────────────────────────────────────────────
// Cross-surface
// ────────────────────────────────────────────────────────────────────────────

export interface Community {
  repo: string
  id: number
  size: number
  modularity?: number
  auto_name?: string
  agent_name?: string
  top_entities: string[]
}

export interface Pattern {
  id: string
  title: string
  description: string
  category: 'code' | 'process' | 'team' | 'tooling' | 'architecture'
  is_candidate: boolean
  is_private?: boolean
  exemplar_ids?: string[]
  anti_exemplar_ids?: string[]
  touches_ids?: string[]
  supersedes_ids?: string[]
  conflicts_with_ids?: string[]
  co_applies_with_ids?: string[]
  prerequisite_ids?: string[]
}

export interface RepairResidual {
  residual_id: string
  repo: string
  action: 'bind_to_entity' | 'reclassify_as_external' | 'reclassify_as_dynamic'
        | 'reclassify_as_resolved' | 'abandon'
  confidence: number
  reasoning?: string
  resolved_at?: string
}

// ────────────────────────────────────────────────────────────────────────────
// Pending queue — repairs + enrichments (Surface 6, #987)
// ────────────────────────────────────────────────────────────────────────────

/** Signals that contributed to the candidate's score (from #1131). */
export type QualificationSignal =
  | 'http_endpoint'
  | 'god_node'
  | 'articulation_point'
  | 'high_pagerank'
  | 'ambiguous_name'
  | 'schema_model'
  | 'data_access'
  | 'service_controller'

/** One row returned by GET /api/repairs/{group} or GET /api/enrichments/{group}. */
export interface PendingCandidateRow {
  candidate_id: string
  repo: string
  kind: string
  subject_id: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  context?: Record<string, any>
  hint?: string
  confidence?: number
  discovered_at?: string
  auto_resolvable?: boolean
  /** 0–100 prioritisation score (issue #1131). Present on enrichment rows. */
  score?: number
  /** Human-readable modifier breakdown, e.g. "base:80 + god_node:20 = 100". */
  score_breakdown?: string
  /** "critical" | "high" | "medium" | "low" */
  criticality_band?: string
  /** Which scoring signals fired for this candidate (#1131). */
  qualification_signals?: QualificationSignal[]
  /** EntityKind of the subject entity (enriched by #1131 backend). */
  entity_kind?: string
}

export interface PendingRepairsResponse {
  items: PendingCandidateRow[]
  total: number
  auto_resolvable_count: number
}

export interface PendingEnrichmentsResponse {
  items: PendingCandidateRow[]
  total: number
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 1 — Graph Viewer
// ────────────────────────────────────────────────────────────────────────────

/**
 * @deprecated LoD removed in #1023 — Cosmograph handles large node counts natively.
 * Kept as a compat alias; value is always 'zoom-in' (dense tier).
 */
export type LodLevel = 'zoom-out' | 'mid' | 'zoom-in' | 'blocked'

/** Flat node as understood by Cosmograph / graph renderers */
export interface GraphNode {
  id: string
  label: string
  kind: EntityKind
  repo: string
  community_id?: number
  pagerank?: number
  /** true when this node is a community centroid (legacy centroid tier — unused since #1023) */
  is_centroid?: boolean
  centroid_size?: number          // member count — legacy centroid data; unused since #1023
  source_file?: string
  start_line?: number
  properties?: Record<string, unknown>
  /** Total in+out edge count, used by Cosmograph pointSizeStrategy="degree" */
  degree?: number
}

/** Flat edge as understood by the graph renderers */
export interface GraphEdge {
  id: string                      // synthetic: `${from_id}::${to_id}::${kind}`
  source: string                  // node id
  target: string                  // node id
  kind: RelationshipKind
  cross_repo?: boolean
}

export interface GraphResponse {
  nodes: GraphNode[]
  edges: GraphEdge[]
  communities: Community[]
  /** @deprecated always 'zoom-in' since #1023 — LoD removed */
  lod: LodLevel
  total_node_count: number
}

export interface GraphFilters {
  edge_kinds?: RelationshipKind[]
  repo?: string
  /** Comma-separated list of repo slugs for multi-repo filtering. */
  repos?: string
  /**
   * When true, External stdlib/builtin placeholder nodes are included.
   * Default server-side is false — external nodes are hidden unless opted in.
   */
  include_external?: boolean
}

/** 1-hop neighbor response for entity inspector */
export interface EntityNeighborResponse {
  entity: Entity
  outbound: Array<{ edge: GraphEdge; node: GraphNode }>
  inbound: Array<{ edge: GraphEdge; node: GraphNode }>
}

// ── Tier 2: Graph labels ──────────────────────────────────────────────────────

/** One entry from GET /api/graph/{group}/labels */
export interface GraphLabelEntry {
  id: string
  label: string
}

/** Response shape of GET /api/graph/{group}/labels */
export interface GraphLabelsResponse {
  labels: GraphLabelEntry[]
}

// ── Patterns surface (#1189) ──────────────────────────────────────────────────

export type PatternStatus = 'active' | 'candidate' | 'rejected'

export interface PatternRow {
  id: string
  kind: string
  category: string
  trigger: string
  confidence: number
  observations: number
  last_seen: string
  status: PatternStatus
  is_candidate: boolean
  needs_attention: boolean
  stale: boolean
  reject_reason?: string
  approval_note?: string
  steps: string[]
  anti_patterns: Array<{ do_not: string; reason: string; private?: boolean }>
  exemplars?: string[]
  touches?: string[]
  scope?: {
    repos?: string[]
    languages?: string[]
    stacks?: string[]
    entity_kinds?: string[]
  }
  convergence_count?: number
}

export interface PatternStats {
  total: number
  pending_review: number
  rejected: number
  stale: number
  needs_attention: number
}

export interface PatternsResponse {
  patterns: PatternRow[]
  count: number
  stats: PatternStats
}

export interface PatternGCResponse {
  dry_run: boolean
  pruned_count: number
  pruned: PatternRow[]
  remaining_count: number
  candidate_decay_days: number
}

export interface PatternExportResponse {
  exported: number
  target: string
}

// ─────────────────────────────────────────────────────────────────────────────
// System / daemon control panel (#1195)
// ─────────────────────────────────────────────────────────────────────────────

/** Wire shape of GET /api/system */
export interface SystemStatus {
  status: 'running' | 'stopped' | 'unhealthy'
  uptime_seconds?: number
  uptime_human?: string
  pid: number
  rss_mb: number
  rss_budget_mb?: number
  socket_path?: string
  dashboard_url?: string
  version: string
  commit_sha: string
  built_at: string
  days_since_build?: number
  stale_build: boolean
}

/** Wire shape of POST /api/system/restart and /api/system/stop */
export interface SystemActionReply {
  ok: boolean
  message: string
}

/** One log line from GET /api/system/logs */
export interface LogLine {
  raw: string
  severity: 'error' | 'warn' | 'info' | 'debug'
}

/** Wire shape of GET /api/system/logs (non-SSE) */
export interface SystemLogsReply {
  lines: LogLine[]
  total: number
  path: string
}

// ─────────────────────────────────────────────────────────────────────────────
// MCP Activity Log (#1226)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * One MCP tool invocation event — mirrors internal/mcp.MCPActivityEvent.
 * Returned by GET /api/mcp-activity/history and streamed via SSE.
 */
export interface MCPActivityEvent {
  tool_name: string
  query_args?: Record<string, unknown>
  returned_node_ids?: string[]
  returned_edge_ids?: string[]
  agent_id?: string
  /** Unix milliseconds */
  timestamp: number
}

/** Wire shape of GET /api/mcp-activity/history?limit=N */
export interface MCPActivityHistoryResponse {
  events: MCPActivityEvent[]
  count: number
  note?: string
}
