// Auto-generated by tygo from internal/types/kinds.go — do not hand-edit entity/relationship kinds.
// All other types are hand-maintained against the JSON shapes returned by REST handlers.

// ────────────────────────────────────────────────────────────────────────────
// Enumerations (from internal/types/kinds.go)
// ────────────────────────────────────────────────────────────────────────────

export type EntityKind =
  | 'Operation' | 'Component' | 'Class' | 'Function'
  | 'Schema' | 'Variable' | 'Reference' | 'Pattern'
  | 'Evolution' | 'Endpoint' | 'Route' | 'Service'
  | 'View' | 'UIComponent' | 'JSX' | 'Stylesheet'
  | 'Queue' | 'Event' | 'Datastore' | 'DataAccess'
  | 'ExternalAPI' | 'InfraResource' | 'CodeBlock'
  | 'Document' | 'Heading' | 'ScopeUnknown'
  | 'External' | 'Project' | 'Config' | 'Model'
  | 'AgentPattern' | 'MessageTopic' | 'Process'

export type RelationshipKind =
  | 'CALLS' | 'IMPORTS' | 'EXTENDS' | 'IMPLEMENTS'
  | 'USES' | 'USES_HOOK' | 'CONTAINS' | 'DEPENDS_ON'
  | 'REFERENCES' | 'ROUTES_TO' | 'SERVES' | 'PUBLISHES_TO'
  | 'TESTS' | 'HAS_PROPS' | 'ACCESSES_TABLE' | 'INJECTED_INTO'
  | 'READS_FROM' | 'WRITES_TO' | 'RENDERS' | 'RETURNS'
  | 'TAGGED_AS'
  | 'EXEMPLAR' | 'TOUCHES' | 'ANTI_EXEMPLAR' | 'SUPERSEDES'
  | 'CONFLICTS_WITH' | 'CO_APPLIES_WITH' | 'PREREQUISITE' | 'CREATED_BY'
  | 'PLATFORM_VARIANT_OF' | 'QUERIES' | 'FETCHES'
  | 'SUBSCRIBES_TO' | 'TRANSFORMS'
  | 'WS_SUBSCRIBES_TO' | 'WS_EMITS' | 'WS_CONNECTS'
  | 'STREAMS_FROM' | 'STREAMS_TO'
  | 'GRAPHQL_SUBSCRIBES' | 'GRAPHQL_PUBLISHES'
  | 'STEP_IN_PROCESS' | 'ENTRY_POINT_OF'

export type HttpVerb = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS' | 'ANY' | 'WS'

// ────────────────────────────────────────────────────────────────────────────
// Core wire types (from internal/mcp/tools.go — serializeEntity)
// ────────────────────────────────────────────────────────────────────────────

export interface Finding {
  question: string
  answer: string
  type: string
  nodes?: string[]
  saved_at: string
}

export interface Entity {
  id: string
  label: string
  qualified_name: string
  kind: EntityKind
  source_file: string
  start_line: number
  end_line: number
  language: string
  repo: string
  pagerank?: number
  community_id?: number
  properties?: Record<string, unknown>
  findings?: Finding[]
}

export interface Relationship {
  from_id: string
  to_id: string
  kind: RelationshipKind
  cross_repo?: boolean
  target_repo?: string
  link_method?: 'http' | 'kafka_topic' | 'ws_channel'
  properties?: Record<string, unknown>
}

// ────────────────────────────────────────────────────────────────────────────
// Registry & groups (GET /api/registry, GET /api/dashboard/init)
// ────────────────────────────────────────────────────────────────────────────

export interface RepoMeta {
  slug: string
  display_name: string
  language: string
  entity_count: number
  indexed_at?: string
}

export interface GroupMeta {
  id: string
  display_name: string
  repos: RepoMeta[]
  entity_count: number
  indexed_at?: string
}

export interface Registry {
  groups: GroupMeta[]
  version: string
}

export interface DashboardInitResponse {
  registry: Registry
  groups: GroupMeta[]
  settings: Record<string, unknown>
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 4 — API & Contracts Explorer (GET /api/paths/{group})
// ────────────────────────────────────────────────────────────────────────────

export interface HttpEndpoint {
  id: string
  repo: string
  verb: HttpVerb
  path: string
  handler: string
  framework?: string
  response_keys?: string[]
  dynamic_response?: boolean
  is_webhook?: boolean
  webhook_provider?: string
  status_codes?: number[]
  inbound_fetches?: string[]
  outbound_queries?: string[]
  language?: string
}

/** A single row in the path list — groups all verbs + endpoints for one unique path string */
export interface PathRow {
  path: string
  path_hash: string
  verbs: HttpVerb[]
  endpoints: HttpEndpoint[]
  multiplicity: number           // total endpoint count for this path (incl. ViewSet expansion)
  repos: string[]                // which repos define handlers for this path
  frameworks: string[]
  is_webhook: boolean
  webhook_provider?: string
}

/** Prefix tree node for the sidebar */
export interface PathTreeNode {
  prefix: string                 // e.g. "/api/v1/"
  label: string                  // display label e.g. "v1"
  count: number                  // total paths under this prefix
  children: PathTreeNode[]
}

export interface PathListResponse {
  paths: PathRow[]
  tree: PathTreeNode[]
  total: number
  has_more: boolean
  page: number
  page_size: number
}

export interface PathFilters {
  prefix?: string
  q?: string
  repo?: string
  framework?: string
  status_code?: number
  is_webhook?: boolean
  page?: number
  page_size?: number
}

/** Full detail for one path — GET /api/paths/{group}/{pathHash} */
export interface HandlerDetail {
  entity: Entity
  verb: HttpVerb
  framework?: string
  source_file: string
  start_line: number
  language: string
}

export interface ResponseShape {
  verb: HttpVerb
  keys: string[]
  dynamic: boolean
  status_codes: number[]
}

export interface PathDetailResponse {
  path: string
  path_hash: string
  verbs: HttpVerb[]
  handlers: HandlerDetail[]
  response_shapes: ResponseShape[]
  inbound_fetches: Entity[]      // entities that FETCHES this path
  outbound_queries: Entity[]     // entities that QUERIES db from handler
  is_webhook: boolean
  webhook_provider?: string
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 2 — Process Flow Explorer
// ────────────────────────────────────────────────────────────────────────────

export interface ProcessStep {
  entity_id: string
  label: string
  source_file: string
  start_line: number
  repo: string
  step_index: number
  edge_kind: RelationshipKind
}

export interface Process {
  process_id: string
  repo: string
  label: string
  entry_id: string
  entry_name: string
  entry_kind?: EntityKind
  terminal_id: string
  step_count: number
  cross_stack: boolean
  crosses_external_lib?: boolean
  terminal_is_phantom?: boolean
  chain_labels: string[]
  source_file?: string
  /** Populated on action=get (detail); absent on action=list */
  steps?: ProcessStep[]
  /** entity_kind of the process entry point (http, kafka_consumer, scheduled, ws_handler) */
  entity_kind?: 'http' | 'kafka_consumer' | 'scheduled' | 'ws_handler'
}

export interface FlowListResponse {
  processes: Process[]
  total: number
  has_more: boolean
}

export interface FlowDetailResponse {
  process: Process
  chain_entities: Entity[]
  source_snippets: Record<string, string>
}

export interface FlowFilters {
  entry?: string
  cross_stack_only?: boolean
  limit?: number
  repo?: string
}

export interface SwimLaneEntry {
  repo: string
  steps: ProcessStep[]
  laneIndex: number
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 3 — Broker Topology
// ────────────────────────────────────────────────────────────────────────────

export interface MessageTopic {
  id: string
  repo: string
  label: string
  broker: string
  producers: string[]
  consumers: string[]
  transforms_to?: string[]
}

export interface QueueNode {
  id: string
  repo: string
  label: string
  broker: string
  producers: string[]
  consumers: string[]
}

export interface ChannelEvent {
  id: string
  repo: string
  label: string
  channel_type: 'websocket' | 'sse' | 'graphql_subscription'
  emitters: string[]
  subscribers: string[]
}

// ────────────────────────────────────────────────────────────────────────────
// Cross-surface
// ────────────────────────────────────────────────────────────────────────────

export interface Community {
  repo: string
  id: number
  size: number
  modularity?: number
  auto_name?: string
  agent_name?: string
  top_entities: string[]
}

export interface Pattern {
  id: string
  title: string
  description: string
  category: 'code' | 'process' | 'team' | 'tooling' | 'architecture'
  is_candidate: boolean
  is_private?: boolean
  exemplar_ids?: string[]
  anti_exemplar_ids?: string[]
  touches_ids?: string[]
  supersedes_ids?: string[]
  conflicts_with_ids?: string[]
  co_applies_with_ids?: string[]
  prerequisite_ids?: string[]
}

export interface RepairResidual {
  residual_id: string
  repo: string
  action: 'bind_to_entity' | 'reclassify_as_external' | 'reclassify_as_dynamic'
        | 'reclassify_as_resolved' | 'abandon'
  confidence: number
  reasoning?: string
  resolved_at?: string
}
