// Auto-generated by tygo from internal/types/kinds.go — do not hand-edit entity/relationship kinds.
// All other types are hand-maintained against the JSON shapes returned by REST handlers.

// ────────────────────────────────────────────────────────────────────────────
// Enumerations (from internal/types/kinds.go)
// ────────────────────────────────────────────────────────────────────────────

export type EntityKind =
  | 'Operation' | 'Component' | 'Class' | 'Function'
  | 'Schema' | 'Variable' | 'Reference' | 'Pattern'
  | 'Evolution' | 'Endpoint' | 'Route' | 'Service'
  | 'View' | 'UIComponent' | 'JSX' | 'Stylesheet'
  | 'Queue' | 'Event' | 'Datastore' | 'DataAccess'
  | 'ExternalAPI' | 'InfraResource' | 'CodeBlock'
  | 'Document' | 'Heading' | 'ScopeUnknown'
  | 'External' | 'Project' | 'Config' | 'Model'
  | 'AgentPattern' | 'MessageTopic' | 'Process'

export type RelationshipKind =
  | 'CALLS' | 'IMPORTS' | 'EXTENDS' | 'IMPLEMENTS'
  | 'USES' | 'USES_HOOK' | 'CONTAINS' | 'DEPENDS_ON'
  | 'REFERENCES' | 'ROUTES_TO' | 'SERVES' | 'PUBLISHES_TO'
  | 'TESTS' | 'HAS_PROPS' | 'ACCESSES_TABLE' | 'INJECTED_INTO'
  | 'READS_FROM' | 'WRITES_TO' | 'RENDERS' | 'RETURNS'
  | 'TAGGED_AS'
  | 'EXEMPLAR' | 'TOUCHES' | 'ANTI_EXEMPLAR' | 'SUPERSEDES'
  | 'CONFLICTS_WITH' | 'CO_APPLIES_WITH' | 'PREREQUISITE' | 'CREATED_BY'
  | 'PLATFORM_VARIANT_OF' | 'QUERIES' | 'FETCHES'
  | 'SUBSCRIBES_TO' | 'TRANSFORMS'
  | 'WS_SUBSCRIBES_TO' | 'WS_EMITS' | 'WS_CONNECTS'
  | 'STREAMS_FROM' | 'STREAMS_TO'
  | 'GRAPHQL_SUBSCRIBES' | 'GRAPHQL_PUBLISHES'
  | 'STEP_IN_PROCESS' | 'ENTRY_POINT_OF'
  /** Synthetic edge between community centroids (zoom-out tier only). */
  | 'COMMUNITY_LINK'

export type HttpVerb = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS' | 'ANY' | 'WS'

// ────────────────────────────────────────────────────────────────────────────
// Core wire types (from internal/mcp/tools.go — serializeEntity)
// ────────────────────────────────────────────────────────────────────────────

export interface Finding {
  question: string
  answer: string
  type: string
  nodes?: string[]
  saved_at: string
}

export interface Entity {
  id: string
  label: string
  qualified_name: string
  kind: EntityKind
  source_file: string
  start_line: number
  end_line: number
  language: string
  repo: string
  pagerank?: number
  community_id?: number
  properties?: Record<string, unknown>
  findings?: Finding[]
}

export interface Relationship {
  from_id: string
  to_id: string
  kind: RelationshipKind
  cross_repo?: boolean
  target_repo?: string
  link_method?: 'http' | 'kafka_topic' | 'ws_channel'
  properties?: Record<string, unknown>
}

// ────────────────────────────────────────────────────────────────────────────
// Registry & groups (GET /api/registry, GET /api/dashboard/init)
// ────────────────────────────────────────────────────────────────────────────

export interface RepoMeta {
  slug: string
  display_name: string
  language: string
  entity_count: number
  indexed_at?: string
}

export interface GroupMeta {
  id: string
  display_name: string
  repos: RepoMeta[]
  entity_count: number
  indexed_at?: string
  /** Unresolved edges percentage for the group (0–100). Percentage of graph edges that point to unknown or ambiguous targets. Present when the group has been indexed. */
  bug_rate?: number
  /** Rolling unresolved edges history (oldest → newest), used for the sparkline. */
  bug_rate_history?: number[]
  /** Top frameworks detected across all repos in the group (sorted by usage, capped at 8). */
  frameworks?: string[]
}

export interface Registry {
  groups: GroupMeta[]
  version: string
}

export interface DashboardInitResponse {
  registry: Registry
  groups: GroupMeta[]
  settings: Record<string, unknown>
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 4 — API & Contracts Explorer (GET /api/paths/{group})
// ────────────────────────────────────────────────────────────────────────────

export interface HttpEndpoint {
  id: string
  repo: string
  verb: HttpVerb
  path: string
  handler: string
  framework?: string
  response_keys?: string[]
  dynamic_response?: boolean
  is_webhook?: boolean
  webhook_provider?: string
  status_codes?: number[]
  inbound_fetches?: string[]
  outbound_queries?: string[]
  language?: string
}

/** A single row in the path list — groups all verbs + endpoints for one unique path string */
export interface PathRow {
  path: string
  path_hash: string
  verbs: HttpVerb[]
  endpoints: HttpEndpoint[]
  multiplicity: number           // total endpoint count for this path (incl. ViewSet expansion)
  repos: string[]                // which repos define handlers for this path
  frameworks: string[]
  is_webhook: boolean
  webhook_provider?: string
  /** Owning controller class / module / router-prefix group (from extractor).
   *  Used for grouped view in Surface 4. */
  controller?: string
}

/** Prefix tree node for the sidebar */
export interface PathTreeNode {
  prefix: string                 // e.g. "/api/v1/"
  label: string                  // display label e.g. "v1"
  count: number                  // total paths under this prefix
  children: PathTreeNode[]
}

export interface PathListResponse {
  paths: PathRow[]
  tree: PathTreeNode[]
  total: number
}

export interface PathFilters {
  prefix?: string
  q?: string
  repo?: string
  framework?: string
  status_code?: number
  is_webhook?: boolean
}

/** Full detail for one path — GET /api/paths/{group}/{pathHash} */
export interface HandlerDetail {
  entity: Entity
  verb: HttpVerb
  framework?: string
  source_file: string
  start_line: number
  language: string
}

export interface ResponseShape {
  verb: HttpVerb
  keys: string[]
  dynamic: boolean
  status_codes: number[]
}

export interface PathDetailResponse {
  path: string
  path_hash: string
  verbs: HttpVerb[]
  handlers: HandlerDetail[]
  response_shapes: ResponseShape[]
  inbound_fetches: Entity[]      // entities that FETCHES this path
  outbound_queries: Entity[]     // entities that QUERIES db from handler
  is_webhook: boolean
  webhook_provider?: string
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 2 — Process Flow Explorer
// ────────────────────────────────────────────────────────────────────────────

export interface ProcessStep {
  entity_id: string
  label: string
  source_file: string
  start_line: number
  repo: string
  step_index: number
  edge_kind: RelationshipKind
}

export interface Process {
  process_id: string
  repo: string
  label: string
  entry_id: string
  entry_name: string
  entry_kind?: EntityKind
  terminal_id: string
  step_count: number
  cross_stack: boolean
  crosses_external_lib?: boolean
  terminal_is_phantom?: boolean
  chain_labels: string[]
  source_file?: string
  /** Populated on action=get (detail); absent on action=list */
  steps?: ProcessStep[]
  /** entity_kind of the process entry point (http, kafka_consumer, scheduled, ws_handler) */
  entity_kind?: 'http' | 'kafka_consumer' | 'scheduled' | 'ws_handler'
}

export interface FlowListResponse {
  processes: Process[]
  total: number
  has_more: boolean
}

export interface FlowDetailResponse {
  process: Process
  chain_entities: Entity[]
  source_snippets: Record<string, string>
}

export interface FlowFilters {
  entry?: string
  cross_stack_only?: boolean
  limit?: number
  repo?: string
}

export interface SwimLaneEntry {
  repo: string
  steps: ProcessStep[]
  laneIndex: number
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 3 — Broker Topology
// ────────────────────────────────────────────────────────────────────────────

export type BrokerProtocol = 'kafka' | 'rabbitmq' | 'sqs' | 'pubsub' | 'nats' | 'redis' | 'redis-stream' | 'task-queue'
export type ChannelProtocol = 'websocket' | 'sse' | 'graphql_subscription' | 'redis_pubsub'
export type ServerlessProtocol = 'serverless'
export type TopologyProtocol = BrokerProtocol | ChannelProtocol | ServerlessProtocol

/** A lightweight entity stub carried in topology responses (avoids re-fetching full Entity) */
export interface TopologyEntityStub {
  id: string
  label: string
  repo: string
  kind: EntityKind
  source_file: string
  start_line: number
}

export interface TopicNode {
  id: string
  repo: string
  label: string
  broker: BrokerProtocol
  producer_ids: string[]
  consumer_ids: string[]
  transforms_to: string[]
}

export interface QueueNode {
  id: string
  repo: string
  label: string
  broker: BrokerProtocol
  queue_type?: 'direct' | 'fanout' | 'standard' | 'fifo' | 'subscription'
  producer_ids: string[]
  consumer_ids: string[]
}

export interface NatsSubject {
  id: string
  repo: string
  label: string
  broker: 'nats'
  producer_ids: string[]
  consumer_ids: string[]
}

export interface ChannelNode {
  id: string
  repo: string
  label: string
  channel_type: ChannelProtocol
  server_endpoint?: string
  emitter_ids: string[]
  subscriber_ids: string[]
}

export interface GraphQLSubscription {
  id: string
  repo: string
  label: string
  schema_type: string
  return_type?: string
  publisher_ids: string[]
  subscriber_ids: string[]
}

export interface TopologyTransform {
  from_id: string
  to_id: string
  transformer_id: string
  repo: string
}

/** A serverless function node — AWS Lambda, GCP Cloud Functions, Azure Functions */
export interface FunctionNode {
  id: string
  repo: string
  label: string
  /** Cloud provider: 'aws-lambda' | 'gcp-cloudfunction' | 'azure-function' | 'serverless' */
  provider: string
  /** Entities that invoke (CALLS) this function */
  invoker_ids: string[]
  /** Entities that handle (HANDLES) this function */
  handler_ids: string[]
}

export interface TopologyResponse {
  topics: TopicNode[]
  queues: QueueNode[]
  channels: ChannelNode[]
  /** Serverless functions (#946) */
  functions: FunctionNode[]
  graphql_subscriptions: GraphQLSubscription[]
  nats_subjects: NatsSubject[]
  transforms: TopologyTransform[]
  producers: Record<string, TopologyEntityStub>
  consumers: Record<string, TopologyEntityStub>
}

export interface TopologyFilters {
  protocols?: TopologyProtocol[]
  topic?: string
}

// ────────────────────────────────────────────────────────────────────────────
// Cross-surface
// ────────────────────────────────────────────────────────────────────────────

export interface Community {
  repo: string
  id: number
  size: number
  modularity?: number
  auto_name?: string
  agent_name?: string
  top_entities: string[]
}

export interface Pattern {
  id: string
  title: string
  description: string
  category: 'code' | 'process' | 'team' | 'tooling' | 'architecture'
  is_candidate: boolean
  is_private?: boolean
  exemplar_ids?: string[]
  anti_exemplar_ids?: string[]
  touches_ids?: string[]
  supersedes_ids?: string[]
  conflicts_with_ids?: string[]
  co_applies_with_ids?: string[]
  prerequisite_ids?: string[]
}

export interface RepairResidual {
  residual_id: string
  repo: string
  action: 'bind_to_entity' | 'reclassify_as_external' | 'reclassify_as_dynamic'
        | 'reclassify_as_resolved' | 'abandon'
  confidence: number
  reasoning?: string
  resolved_at?: string
}

// ────────────────────────────────────────────────────────────────────────────
// Pending queue — repairs + enrichments (Surface 6, #987)
// ────────────────────────────────────────────────────────────────────────────

/** One row returned by GET /api/repairs/{group} or GET /api/enrichments/{group}. */
export interface PendingCandidateRow {
  candidate_id: string
  repo: string
  kind: string
  subject_id: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  context?: Record<string, any>
  hint?: string
  confidence?: number
  discovered_at?: string
  auto_resolvable?: boolean
}

export interface PendingRepairsResponse {
  items: PendingCandidateRow[]
  total: number
  auto_resolvable_count: number
}

export interface PendingEnrichmentsResponse {
  items: PendingCandidateRow[]
  total: number
}

// ────────────────────────────────────────────────────────────────────────────
// Surface 1 — Graph Viewer
// ────────────────────────────────────────────────────────────────────────────

/**
 * @deprecated LoD removed in #1023 — Cosmograph handles large node counts natively.
 * Kept as a compat alias; value is always 'zoom-in' (dense tier).
 */
export type LodLevel = 'zoom-out' | 'mid' | 'zoom-in' | 'blocked'

/** Flat node as understood by Cosmograph / graph renderers */
export interface GraphNode {
  id: string
  label: string
  kind: EntityKind
  repo: string
  community_id?: number
  pagerank?: number
  /** true when this node is a community centroid (legacy centroid tier — unused since #1023) */
  is_centroid?: boolean
  centroid_size?: number          // member count — legacy centroid data; unused since #1023
  source_file?: string
  start_line?: number
  properties?: Record<string, unknown>
}

/** Flat edge as understood by the graph renderers */
export interface GraphEdge {
  id: string                      // synthetic: `${from_id}::${to_id}::${kind}`
  source: string                  // node id
  target: string                  // node id
  kind: RelationshipKind
  cross_repo?: boolean
}

export interface GraphResponse {
  nodes: GraphNode[]
  edges: GraphEdge[]
  communities: Community[]
  /** @deprecated always 'zoom-in' since #1023 — LoD removed */
  lod: LodLevel
  total_node_count: number
}

export interface GraphFilters {
  edge_kinds?: RelationshipKind[]
  repo?: string
  /** Comma-separated list of repo slugs for multi-repo filtering. */
  repos?: string
}

/** 1-hop neighbor response for entity inspector */
export interface EntityNeighborResponse {
  entity: Entity
  outbound: Array<{ edge: GraphEdge; node: GraphNode }>
  inbound: Array<{ edge: GraphEdge; node: GraphNode }>
}
