package resolve

import "regexp"

// groovyDynamicPatterns are per-language patterns for Groovy, Grails, and Gradle.
// Groovy is a JVM language, so it inherits all jvmDynamicPatterns in addition to
// Groovy/Grails/Gradle-specific patterns. Registered via init() into dynamicPatternsByLang.
//
// Issue #44 — Groovy/Grails/Gradle dynamic patterns. These cover the dispatch
// that is specific to Groovy's DSL capabilities and the Grails framework, which
// uses runtime metaclass injection to add framework-specific methods to domain
// classes, controllers, and test classes. Categories:
//
//  1. Grails controller DSL — methods injected by the Grails runtime via
//     RestfulController / GrailsControllerClass metaclass. The extractor
//     emits bare leaf identifiers; the resolver cannot bind them to a
//     static declaration because they are added at startup through Groovy
//     metaclass injection.
//
//  2. GORM dynamic finders — generated at runtime by the GORM framework.
//     `save`, `delete`, `get`, `list`, `count`, `findAll`, `find`,
//     `findBy*`, `findAllBy*`, `countBy*`, `reload`, etc. are synthesised
//     by GORM and never appear as static method declarations. The
//     per-language gate keeps `save`/`delete`/`get` from being classified
//     Dynamic in Java/Kotlin/Python where they may be user-defined.
//
//  3. Spock specification DSL — `thrown`, `notThrown`, `old`, `Mock`,
//     `Stub`, `Spy`, `mockDomains`, `where`, etc. are Spock-injected
//     identifiers whose resolution requires the Spock compiler AST
//     transformation; static resolvers see only bare leaves.
//
//  4. Gradle DSL method calls — `doLast`, `doFirst`, `dependsOn`,
//     `from`, `into`, `configurations`, `sourceSets`, `repositories`,
//     `dependencies`, `implementation`, `testImplementation`, `compile`,
//     etc. are Groovy DSL closures evaluated against the project object.
//     The extractor surfaces them as bare-name CALLS; they cannot be
//     statically resolved against any in-tree entity.
//
//  5. GrailsApp entry point — `GrailsApp.run(...)` is the Grails boot
//     idiom; the qualified form can't be resolved without external
//     grails-boot on the classpath.
var groovyDynamicPatterns = []*regexp.Regexp{
	// -- 1. Grails controller DSL ----------------------------------
	// RestfulController-inherited template methods.
	regexp.MustCompile(`^findResource$`),    // RestfulController.findResource(id)
	regexp.MustCompile(`^bindData$`),        // bindData(domain, request)
	regexp.MustCompile(`^respond$`),         // respond <value>
	regexp.MustCompile(`^render$`),          // render view: 'show'
	regexp.MustCompile(`^redirect$`),        // redirect action: 'index'
	regexp.MustCompile(`^forward$`),         // forward action: 'create'
	regexp.MustCompile(`^chain$`),           // chain action: 'create'
	regexp.MustCompile(`^withFormat$`),      // withFormat { json { ... } }
	regexp.MustCompile(`^withTransaction$`), // withTransaction { status -> ... }
	// Transaction lifecycle.
	regexp.MustCompile(`^setRollbackOnly$`), // transactionStatus.setRollbackOnly()

	// -- 2. GORM dynamic finders / persistence DSL -----------------
	// Domain class static methods generated by GORM metaclass.
	regexp.MustCompile(`^save$`),     // domainObj.save(flush: true)
	regexp.MustCompile(`^delete$`),   // domainObj.delete()
	regexp.MustCompile(`^reload$`),   // domainObj.reload()
	regexp.MustCompile(`^refresh$`),  // domainObj.refresh()
	regexp.MustCompile(`^discard$`),  // domainObj.discard()
	regexp.MustCompile(`^attach$`),   // domainObj.attach()
	regexp.MustCompile(`^validate$`), // domainObj.validate()
	regexp.MustCompile(`^count$`),    // DomainClass.count()
	regexp.MustCompile(`^findAll$`),  // DomainClass.findAll()
	regexp.MustCompile(`^findAllWhere$`),
	regexp.MustCompile(`^findWhere$`),
	regexp.MustCompile(`^findOrSave$`),
	regexp.MustCompile(`^findOrCreate$`),
	regexp.MustCompile(`^list$`),           // DomainClass.list(max: N)
	regexp.MustCompile(`^exists$`),         // DomainClass.exists(id)
	regexp.MustCompile(`^withCriteria$`),   // DomainClass.withCriteria { ... }
	regexp.MustCompile(`^createCriteria$`), // DomainClass.createCriteria()
	regexp.MustCompile(`^executeQuery$`),   // DomainClass.executeQuery(hql)
	regexp.MustCompile(`^executeUpdate$`),  // DomainClass.executeUpdate(hql)
	regexp.MustCompile(`^withNewSession$`), // DomainClass.withNewSession { ... }
	regexp.MustCompile(`^withSession$`),    // DomainClass.withSession { ... }
	// Dynamic finder family — findBy*, findAllBy*, countBy*, getBy*.
	// Anchored prefix pattern to match generated method names without
	// hard-coding the hundreds of possible property combinations.
	regexp.MustCompile(`^findBy[A-Z]`),    // findByEmail, findByStatus, etc.
	regexp.MustCompile(`^findAllBy[A-Z]`), // findAllByStatus, etc.
	regexp.MustCompile(`^countBy[A-Z]`),   // countByStatus, etc.
	regexp.MustCompile(`^getBy[A-Z]`),     // getByName, etc.

	// -- 3. Spock test DSL ----------------------------------------
	// Methods injected by the Spock compiler / runtime.
	regexp.MustCompile(`^thrown$`),      // thrown(ExceptionClass)
	regexp.MustCompile(`^notThrown$`),   // notThrown(ExceptionClass)
	regexp.MustCompile(`^old$`),         // old(expression) in then: blocks
	regexp.MustCompile(`^Mock$`),        // Mock(ServiceClass)
	regexp.MustCompile(`^Stub$`),        // Stub(ServiceClass)
	regexp.MustCompile(`^Spy$`),         // Spy(ServiceClass)
	regexp.MustCompile(`^mockDomains$`), // mockDomains Post, User — DataTest DSL
	regexp.MustCompile(`^interaction$`), // interaction { ... }
	regexp.MustCompile(`^noExceptionThrown$`),

	// -- 4. Gradle build script DSL -------------------------------
	// Project-object closure methods; resolved at build-script eval
	// time against the org.gradle.api.Project instance.
	regexp.MustCompile(`^doLast$`),    // task.doLast { ... }
	regexp.MustCompile(`^doFirst$`),   // task.doFirst { ... }
	regexp.MustCompile(`^dependsOn$`), // task.dependsOn('other')
	regexp.MustCompile(`^mustRunAfter$`),
	regexp.MustCompile(`^shouldRunAfter$`),
	regexp.MustCompile(`^finalizedBy$`),
	regexp.MustCompile(`^from$`),       // CopySpec.from(...)
	regexp.MustCompile(`^into$`),       // CopySpec.into(...)
	regexp.MustCompile(`^include$`),    // CopySpec.include(...)
	regexp.MustCompile(`^exclude$`),    // CopySpec.exclude(...)
	regexp.MustCompile(`^sourceSets$`), // project.sourceSets
	regexp.MustCompile(`^configurations$`),
	regexp.MustCompile(`^repositories$`),
	regexp.MustCompile(`^dependencies$`),
	regexp.MustCompile(`^implementation$`),
	regexp.MustCompile(`^testImplementation$`),
	regexp.MustCompile(`^runtimeOnly$`),
	regexp.MustCompile(`^compileOnly$`),
	regexp.MustCompile(`^testRuntimeOnly$`),
	regexp.MustCompile(`^testCompileOnly$`),
	regexp.MustCompile(`^api$`),          // API dependency (java-library plugin)
	regexp.MustCompile(`^mavenCentral$`), // repositories { mavenCentral() }
	regexp.MustCompile(`^mavenLocal$`),
	regexp.MustCompile(`^jcenter$`),
	regexp.MustCompile(`^google$`),
	regexp.MustCompile(`^gradlePluginPortal$`),
	regexp.MustCompile(`^buildscript$`), // buildscript { ... }
	regexp.MustCompile(`^allprojects$`), // allprojects { ... }
	regexp.MustCompile(`^subprojects$`), // subprojects { ... }
	regexp.MustCompile(`^configure$`),   // configure(project) { ... }
	regexp.MustCompile(`^project$`),     // project(':sub') { ... }
	regexp.MustCompile(`^ext$`),         // ext { prop = value }
	regexp.MustCompile(`^println$`),     // Groovy/Gradle println (top-level)

	// -- 5. GrailsApp entry point ---------------------------------
	regexp.MustCompile(`^GrailsApp\.run$`), // GrailsApp.run(Application, args)
}

func init() {
	// Groovy inherits all JVM patterns (reflection, ServiceLoader, Spring ResponseEntity)
	// and adds Groovy/Grails/Gradle-specific patterns.
	combined := append([]*regexp.Regexp{}, jvmDynamicPatterns...)
	combined = append(combined, groovyDynamicPatterns...)
	dynamicPatternsByLang["groovy"] = combined
}
