// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbgraph

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Graph struct {
	_tab flatbuffers.Table
}

func GetRootAsGraph(buf []byte, offset flatbuffers.UOffsetT) *Graph {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Graph{}
	x.Init(buf, n+offset)
	return x
}

func FinishGraphBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGraph(buf []byte, offset flatbuffers.UOffsetT) *Graph {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Graph{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGraphBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Graph) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Graph) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Graph) Version() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 2
}

func (rcv *Graph) MutateVersion(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Graph) ComputedAt() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Graph) RepoTag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Graph) Entities(obj *Entity, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Graph) EntitiesByKey(obj *Entity, key string) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		return obj.LookupByKey(key, x, rcv._tab.Bytes)
	}
	return false
}

func (rcv *Graph) EntitiesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Graph) Relationships(obj *Relationship, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Graph) RelationshipsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Graph) Communities(obj *Community, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Graph) CommunitiesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Graph) LouvainModularity() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Graph) MutateLouvainModularity(n float64) bool {
	return rcv._tab.MutateFloat64Slot(16, n)
}

func (rcv *Graph) NumGodNodes() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Graph) MutateNumGodNodes(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func (rcv *Graph) NumArticulationPoints() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Graph) MutateNumArticulationPoints(n int32) bool {
	return rcv._tab.MutateInt32Slot(20, n)
}

func (rcv *Graph) NumSurpriseEdges() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Graph) MutateNumSurpriseEdges(n int32) bool {
	return rcv._tab.MutateInt32Slot(22, n)
}

func (rcv *Graph) AlgoRuntimeMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Graph) MutateAlgoRuntimeMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(24, n)
}

func (rcv *Graph) DenoisedCommunities() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Graph) MutateDenoisedCommunities(n int32) bool {
	return rcv._tab.MutateInt32Slot(26, n)
}

func (rcv *Graph) IndexedRef() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Graph) IndexedSha() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Graph) IsWorktree() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Graph) MutateIsWorktree(n bool) bool {
	return rcv._tab.MutateBoolSlot(32, n)
}

// CoverageStatus returns the coverage status string ("" / "full" / "partial").
// Field slot 15 / vtable offset 34 — appended after is_worktree (#2181 / M4).
// Returns nil (empty) for graphs written before this field was added.
func (rcv *Graph) CoverageStatus() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GraphStart(builder *flatbuffers.Builder) {
	builder.StartObject(16)
}
func GraphAddVersion(builder *flatbuffers.Builder, version int32) {
	builder.PrependInt32Slot(0, version, 2)
}
func GraphAddComputedAt(builder *flatbuffers.Builder, computedAt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(computedAt), 0)
}
func GraphAddRepoTag(builder *flatbuffers.Builder, repoTag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(repoTag), 0)
}
func GraphAddEntities(builder *flatbuffers.Builder, entities flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(entities), 0)
}
func GraphStartEntitiesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GraphAddRelationships(builder *flatbuffers.Builder, relationships flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(relationships), 0)
}
func GraphStartRelationshipsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GraphAddCommunities(builder *flatbuffers.Builder, communities flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(communities), 0)
}
func GraphStartCommunitiesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GraphAddLouvainModularity(builder *flatbuffers.Builder, louvainModularity float64) {
	builder.PrependFloat64Slot(6, louvainModularity, 0.0)
}
func GraphAddNumGodNodes(builder *flatbuffers.Builder, numGodNodes int32) {
	builder.PrependInt32Slot(7, numGodNodes, 0)
}
func GraphAddNumArticulationPoints(builder *flatbuffers.Builder, numArticulationPoints int32) {
	builder.PrependInt32Slot(8, numArticulationPoints, 0)
}
func GraphAddNumSurpriseEdges(builder *flatbuffers.Builder, numSurpriseEdges int32) {
	builder.PrependInt32Slot(9, numSurpriseEdges, 0)
}
func GraphAddAlgoRuntimeMs(builder *flatbuffers.Builder, algoRuntimeMs int64) {
	builder.PrependInt64Slot(10, algoRuntimeMs, 0)
}
func GraphAddDenoisedCommunities(builder *flatbuffers.Builder, denoisedCommunities int32) {
	builder.PrependInt32Slot(11, denoisedCommunities, 0)
}
func GraphAddIndexedRef(builder *flatbuffers.Builder, indexedRef flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(indexedRef), 0)
}
func GraphAddIndexedSha(builder *flatbuffers.Builder, indexedSha flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(indexedSha), 0)
}
func GraphAddIsWorktree(builder *flatbuffers.Builder, isWorktree bool) {
	builder.PrependBoolSlot(14, isWorktree, false)
}

// GraphAddCoverageStatus writes the M4 sparse-checkout coverage_status field
// (#2181). Slot 15, vtable offset 34. Empty string = omitted by FlatBuffers.
func GraphAddCoverageStatus(builder *flatbuffers.Builder, coverageStatus flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(15, flatbuffers.UOffsetT(coverageStatus), 0)
}

func GraphEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
