// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbgraph

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PropertyEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsPropertyEntry(buf []byte, offset flatbuffers.UOffsetT) *PropertyEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PropertyEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishPropertyEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPropertyEntry(buf []byte, offset flatbuffers.UOffsetT) *PropertyEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PropertyEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPropertyEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PropertyEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PropertyEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PropertyEntry) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PropertyEntry) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PropertyEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PropertyEntryAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func PropertyEntryAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func PropertyEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
