// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbgraph

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Relationship struct {
	_tab flatbuffers.Table
}

func GetRootAsRelationship(buf []byte, offset flatbuffers.UOffsetT) *Relationship {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Relationship{}
	x.Init(buf, n+offset)
	return x
}

func FinishRelationshipBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRelationship(buf []byte, offset flatbuffers.UOffsetT) *Relationship {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Relationship{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRelationshipBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Relationship) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Relationship) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Relationship) FromId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Relationship) ToId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Relationship) Kind() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Relationship) Properties(obj *PropertyEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Relationship) PropertiesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RelationshipStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func RelationshipAddFromId(builder *flatbuffers.Builder, fromId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(fromId), 0)
}
func RelationshipAddToId(builder *flatbuffers.Builder, toId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(toId), 0)
}
func RelationshipAddKind(builder *flatbuffers.Builder, kind flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(kind), 0)
}
func RelationshipAddProperties(builder *flatbuffers.Builder, properties flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(properties), 0)
}
func RelationshipStartPropertiesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RelationshipEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
