// Tests for the Lombok synthetic-source-stub helper (issue #1998).
//
// buildLombokSynthStub must fabricate a believable Java accessor body for
// Lombok-synthesised Operations whose source_window helper returned empty
// (because the accessor has no real source — it exists only post-compile).

package docgen

import (
	"strings"
	"testing"

	"github.com/cajasmota/grafel/internal/graph"
)

func TestBuildLombokSynthStub_DataGetter(t *testing.T) {
	e := &graph.Entity{
		Name:      "ListRequest.getPageSize",
		Kind:      "SCOPE.Operation",
		Subtype:   "method",
		Signature: "Integer getPageSize()",
		Properties: map[string]string{
			"synthesized_from": "lombok_data",
			"pattern_type":     "lombok_accessor",
			"accessor_kind":    "getter",
			"field":            "pageSize",
		},
	}
	stub := buildLombokSynthStub(e)
	if stub == "" {
		t.Fatalf("expected non-empty stub for lombok @Data getter")
	}
	for _, want := range []string{
		"@Data synthesised getter for field `pageSize`",
		"Integer getPageSize()",
		"return pageSize",
	} {
		if !strings.Contains(stub, want) {
			t.Errorf("stub missing %q\n----\n%s\n----", want, stub)
		}
	}
}

func TestBuildLombokSynthStub_DataSetter(t *testing.T) {
	e := &graph.Entity{
		Name:      "ListRequest.setPageSize",
		Kind:      "SCOPE.Operation",
		Subtype:   "method",
		Signature: "void setPageSize(Integer pageSize)",
		Properties: map[string]string{
			"synthesized_from": "lombok_data",
			"pattern_type":     "lombok_accessor",
			"accessor_kind":    "setter",
			"field":            "pageSize",
		},
	}
	stub := buildLombokSynthStub(e)
	if !strings.Contains(stub, "this.pageSize = pageSize") {
		t.Errorf("setter stub missing assignment, got:\n%s", stub)
	}
	if !strings.Contains(stub, "@Data synthesised setter") {
		t.Errorf("setter stub missing annotation label, got:\n%s", stub)
	}
}

func TestBuildLombokSynthStub_GetterAnnotation(t *testing.T) {
	e := &graph.Entity{
		Name:      "Product.getName",
		Kind:      "SCOPE.Operation",
		Subtype:   "method",
		Signature: "String getName()",
		Properties: map[string]string{
			"synthesized_from": "lombok_getter",
			"pattern_type":     "lombok_accessor",
			"accessor_kind":    "getter",
			"field":            "name",
		},
	}
	stub := buildLombokSynthStub(e)
	if !strings.Contains(stub, "@Getter") {
		t.Errorf("expected @Getter label, got:\n%s", stub)
	}
}

func TestBuildLombokSynthStub_NoLombokProperty(t *testing.T) {
	e := &graph.Entity{
		Name:    "RealClass.realMethod",
		Kind:    "SCOPE.Operation",
		Subtype: "method",
		Properties: map[string]string{
			"some_other_prop": "x",
		},
	}
	if stub := buildLombokSynthStub(e); stub != "" {
		t.Errorf("expected empty stub for non-lombok entity, got: %q", stub)
	}
}

func TestBuildLombokSynthStub_NilEntity(t *testing.T) {
	if stub := buildLombokSynthStub(nil); stub != "" {
		t.Errorf("expected empty stub for nil entity, got: %q", stub)
	}
}

func TestBuildLombokSynthStub_NonAccessorMethod(t *testing.T) {
	// equals/hashCode/toString: no accessor_kind, signature present.
	e := &graph.Entity{
		Name:      "User.toString",
		Kind:      "SCOPE.Operation",
		Signature: "String toString()",
		Properties: map[string]string{
			"synthesized_from": "lombok_data",
			"pattern_type":     "lombok_accessor",
		},
	}
	stub := buildLombokSynthStub(e)
	if !strings.Contains(stub, "toString") {
		t.Errorf("non-accessor stub missing method name, got:\n%s", stub)
	}
	if !strings.Contains(stub, "generated by Lombok") {
		t.Errorf("non-accessor stub missing generated marker, got:\n%s", stub)
	}
}
