// Package docgen — Lombok synthetic source stub (issue #1998).
//
// When the indexer emits an Operation entity for a Lombok-generated accessor
// (@Data / @Getter / @Setter / @With / @Builder etc.), there is no real
// source code in the .java file: the method exists only at compile time.
// docgen's source_window helper therefore returns an empty string for these
// entities, and the LLM is left documenting an accessor blind — invisible to
// bean-validation propagation, invisible to @Valid, invisible in shape trees.
//
// buildLombokSynthStub fabricates a believable stub that captures everything
// a docgen reader needs: the accessor's signature, the field it covers, and
// a header comment naming the originating Lombok annotation. It is
// deterministic — same entity in, same string out — so bundle byte-equality
// for golden tests stays intact.
//
// The stub is emitted only when:
//   - entity.Properties["synthesized_from"] starts with "lombok_"
//   - the regular source_window helper produced nothing
//
// Source-window-fallback is flagged on the bundle so downstream tooling can
// audit how often the stub fires.

package docgen

import (
	"fmt"
	"strings"

	"github.com/cajasmota/grafel/internal/graph"
)

// buildLombokSynthStub returns a synthetic Java source excerpt for the
// Lombok-synthesised entity, or the empty string when the entity is not a
// Lombok synthesisation. The stub looks like real Java so the LLM can pattern
// match the accessor shape; it intentionally avoids fabricating bodies for
// non-accessor synthesisations (toString/equals/hashCode, builders) — those
// emit a one-line `// generated by Lombok` comment.
func buildLombokSynthStub(entity *graph.Entity) string {
	if entity == nil || entity.Properties == nil {
		return ""
	}
	synthFrom := entity.Properties["synthesized_from"]
	if !strings.HasPrefix(synthFrom, "lombok_") {
		return ""
	}

	accessorKind := entity.Properties["accessor_kind"]
	field := entity.Properties["field"]
	signature := entity.Signature

	// Display name of the annotation, e.g. "lombok_data" -> "@Data".
	annLabel := lombokAnnotationLabel(synthFrom)

	// Bare-method name (strip "<Class>." prefix from entity.Name if present).
	methodName := entity.Name
	if dot := strings.LastIndex(methodName, "."); dot >= 0 {
		methodName = methodName[dot+1:]
	}

	var b strings.Builder
	switch accessorKind {
	case "getter":
		fmt.Fprintf(&b, "// Lombok %s synthesised getter for field `%s`.\n", annLabel, field)
		fmt.Fprintf(&b, "// No real source — generated at compile time by Lombok.\n")
		fmt.Fprintf(&b, "public %s { return %s; }\n", signature, field)
	case "setter":
		fmt.Fprintf(&b, "// Lombok %s synthesised setter for field `%s`.\n", annLabel, field)
		fmt.Fprintf(&b, "// No real source — generated at compile time by Lombok.\n")
		fmt.Fprintf(&b, "public %s { this.%s = %s; }\n", signature, field, field)
	case "wither":
		fmt.Fprintf(&b, "// Lombok %s synthesised wither for field `%s` (returns a copy).\n", annLabel, field)
		fmt.Fprintf(&b, "// No real source — generated at compile time by Lombok.\n")
		fmt.Fprintf(&b, "public %s { /* returns a copy with %s replaced */ }\n", signature, field)
	default:
		// Non-accessor synthesisation (constructor / builder / equals /
		// hashCode / toString / builder-class methods). Emit a one-line
		// comment plus the signature so the LLM at least sees the shape.
		if signature == "" && methodName == "" {
			return ""
		}
		fmt.Fprintf(&b, "// Lombok %s synthesised method `%s` — no real source.\n", annLabel, methodName)
		if signature != "" {
			fmt.Fprintf(&b, "public %s { /* generated by Lombok */ }\n", signature)
		}
	}
	return b.String()
}

// lombokAnnotationLabel maps a synthesized_from tag (e.g. "lombok_data") to
// its user-facing annotation form ("@Data"). Falls back to the tag itself
// when the mapping is unknown so future Lombok additions still render.
func lombokAnnotationLabel(synthFrom string) string {
	switch synthFrom {
	case "lombok_data":
		return "@Data"
	case "lombok_value":
		return "@Value"
	case "lombok_getter":
		return "@Getter"
	case "lombok_setter":
		return "@Setter"
	case "lombok_with":
		return "@With"
	case "lombok_builder":
		return "@Builder"
	case "lombok_super_builder":
		return "@SuperBuilder"
	case "lombok_all_args_constructor":
		return "@AllArgsConstructor"
	case "lombok_required_args_constructor":
		return "@RequiredArgsConstructor"
	case "lombok_no_args_constructor":
		return "@NoArgsConstructor"
	case "lombok_accessors_chain":
		return "@Accessors(chain=true)"
	default:
		return "@" + strings.TrimPrefix(synthFrom, "lombok_")
	}
}
