package main

import (
	"context"
	"fmt"
	"io"
	"sort"
	"time"
)

// Result is one grammar's freshness verdict.
type Result struct {
	Language string
	Source   string
	// BundledDate is the smacker snapshot date the grammar is frozen at.
	BundledDate string
	// UpstreamRelease / UpstreamCommitDate are the live upstream state.
	UpstreamRelease    string
	UpstreamCommitDate string
	UpstreamKind       string // "release" | "commit"
	// Behind is the gap between the bundled snapshot and the upstream commit.
	Behind time.Duration
	Stale  bool
	// Err is set when the upstream lookup failed; the grammar is reported as
	// "unknown" (skipped, not counted stale, not a hard failure on its own).
	Err error
}

// Report is the full A2 result set.
type Report struct {
	Binding      Binding
	LastVerified string
	CheckedAt    time.Time
	Grammars     []Result
	StaleCount   int
	Errored      int
}

// check fans out over every grammar in the lock, resolving each upstream and
// comparing to the bundled snapshot. Errors on individual grammars are captured
// per-result (resilient) rather than aborting the run.
func check(ctx context.Context, lock *Lock, src UpstreamSource) Report {
	rep := Report{
		Binding:      lock.Binding,
		LastVerified: lock.LastVerified,
		CheckedAt:    time.Now().UTC(),
	}

	// The bundled date is the same smacker snapshot for every grammar.
	bundled := parseDate(lock.Binding.PinnedDate)

	for _, g := range lock.Grammars {
		r := Result{
			Language:    g.Language,
			Source:      g.Source,
			BundledDate: lock.Binding.PinnedDate,
		}
		up, err := src.Latest(ctx, g.Source)
		if err != nil {
			r.Err = err
			rep.Errored++
			rep.Grammars = append(rep.Grammars, r)
			continue
		}
		r.UpstreamRelease = up.Release
		r.UpstreamCommitDate = up.CommitDate
		r.UpstreamKind = up.Kind

		// Staleness = upstream has a commit newer than the bundled snapshot.
		if upd := parseDate(up.CommitDate); !upd.IsZero() && !bundled.IsZero() {
			if upd.After(bundled) {
				r.Stale = true
				r.Behind = upd.Sub(bundled)
			}
		}
		if r.Stale {
			rep.StaleCount++
		}
		rep.Grammars = append(rep.Grammars, r)
	}

	// Stable order: stale first (most behind first), then current, then errored.
	sort.SliceStable(rep.Grammars, func(i, j int) bool {
		a, b := rep.Grammars[i], rep.Grammars[j]
		rank := func(r Result) int {
			switch {
			case r.Err != nil:
				return 2
			case r.Stale:
				return 0
			default:
				return 1
			}
		}
		if ra, rb := rank(a), rank(b); ra != rb {
			return ra < rb
		}
		if a.Behind != b.Behind {
			return a.Behind > b.Behind
		}
		return a.Language < b.Language
	})
	return rep
}

func parseDate(s string) time.Time {
	t, err := time.Parse("2006-01-02", s)
	if err != nil {
		return time.Time{}
	}
	return t
}

// months renders a duration as an approximate whole-month count for humans.
func months(d time.Duration) int {
	return int(d.Hours() / 24 / 30.4)
}

func writeTable(w io.Writer, r Report) {
	fmt.Fprintf(w, "grammar freshness (A2) — checked %s\n", r.CheckedAt.Format("2006-01-02"))
	fmt.Fprintf(w, "binding: %s %s (snapshot %s, unmaintained)\n",
		r.Binding.Module, r.Binding.Version, r.Binding.PinnedDate)
	fmt.Fprintf(w, "%d grammars: %d stale, %d current, %d unreachable\n\n",
		len(r.Grammars), r.StaleCount, len(r.Grammars)-r.StaleCount-r.Errored, r.Errored)

	fmt.Fprintf(w, "%-12s %-10s %-12s %-12s %s\n", "LANGUAGE", "STATUS", "BUNDLED", "UPSTREAM", "DETAIL")
	for _, g := range r.Grammars {
		switch {
		case g.Err != nil:
			fmt.Fprintf(w, "%-12s %-10s %-12s %-12s %v\n", g.Language, "UNKNOWN", g.BundledDate, "-", g.Err)
		case g.Stale:
			rel := g.UpstreamRelease
			if rel == "" {
				rel = "(no release)"
			}
			fmt.Fprintf(w, "%-12s %-10s %-12s %-12s ~%d mo behind, upstream %s @ %s\n",
				g.Language, "STALE", g.BundledDate, g.UpstreamCommitDate, months(g.Behind), rel, g.UpstreamCommitDate)
		default:
			fmt.Fprintf(w, "%-12s %-10s %-12s %-12s up to date\n",
				g.Language, "CURRENT", g.BundledDate, g.UpstreamCommitDate)
		}
	}
}

// writeMarkdown renders the body for the tracking issue. It is deterministic
// (no timestamp churn beyond the checked date) so re-running on an unchanged
// graph produces a stable body — the workflow only edits the issue when content
// actually changes.
func writeMarkdown(w io.Writer, r Report) {
	fmt.Fprintf(w, "## Grammar freshness — %d of %d grammars stale\n\n", r.StaleCount, len(r.Grammars))
	fmt.Fprintf(w, "_Auto-generated by the `grammar-freshness` monthly cron (A2, epic #5359). Last checked **%s**._\n\n",
		r.CheckedAt.Format("2006-01-02"))
	fmt.Fprintf(w, "The grammars are bundled via `%s` (`%s`, snapshot **%s**), which is unmaintained at its own upstream HEAD. This alarm therefore tracks each `tree-sitter/tree-sitter-<lang>` repo **independently** of the binding. Most/all grammars being stale is expected until the B2 migration lands.\n\n",
		r.Binding.Module, r.Binding.Version, r.Binding.PinnedDate)

	if r.StaleCount > 0 {
		fmt.Fprintf(w, "### Stale grammars\n\n")
		fmt.Fprintf(w, "| Language | Upstream repo | Bundled | Upstream latest | Behind |\n")
		fmt.Fprintf(w, "|---|---|---|---|---|\n")
		for _, g := range r.Grammars {
			if !g.Stale {
				continue
			}
			rel := g.UpstreamRelease
			if rel == "" {
				rel = "_(no release — default branch)_"
			}
			fmt.Fprintf(w, "| %s | [`%s`](https://github.com/%s) | %s | %s @ %s | ~%d mo |\n",
				g.Language, g.Source, g.Source, g.BundledDate, rel, g.UpstreamCommitDate, months(g.Behind))
		}
		fmt.Fprintln(w)
	} else {
		fmt.Fprintf(w, "All grammars are current against their upstream. \n\n")
	}

	if r.Errored > 0 {
		fmt.Fprintf(w, "### Unreachable (skipped, re-check next run)\n\n")
		for _, g := range r.Grammars {
			if g.Err != nil {
				fmt.Fprintf(w, "- `%s` (%s): %v\n", g.Language, g.Source, g.Err)
			}
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintf(w, "---\nPart of epic #5359 (milestone 0.1.4). See `docs/grammar-freshness-audit.md` and `grammars.lock`.\n")
}
