// handlers_v2_docs.go — WebUI v2 generated-markdown docs endpoints.
//
// These endpoints serve the /g/:groupId/docs screen in webui-v2.
//
// IMPORTANT (#1552, updated #1624): The Docs screen renders the MARKDOWN
// DOCUMENTS produced by the `generate-docs` skill — NOT the entity graph.
// Docs are generated by the user's coding AGENT running the grafel docs
// skill (there is no CLI command). As of #1624 the skill writes into the
// daemon-managed store, NOT into the source repos:
//
//	~/.grafel/docs/<group>/<repoSlug>/overview.md
//	~/.grafel/docs/<group>/<repoSlug>/modules/<module-slug>/README.md
//	~/.grafel/docs/<group>/<repoSlug>/reference/<section>.md
//	~/.grafel/docs/<group>/<repoSlug>/patterns/<category>/<id>.md
//	~/.grafel/docs/<group>/<repoSlug>/<cross-cutting>.md
//	~/.grafel/docs/<group>/business/...   (business tier, group-synthesised)
//
// Pre-#1624 in-repo `<repo>/docs/` directories are migrated into the store on
// first read (see daemon.MigrateInRepoDocs), and kept as a read-only fallback
// for groups that have not been re-generated since the move.
//
// These v2 endpoints reuse the on-disk doc resolution from handlers_docs.go
// (groupDocPaths / buildDocTree) and wrap it in the v2 success envelope. The
// v1 /api/docs/{group} portal endpoints are left completely untouched.
//
// Routes (registered in server.go under the v2 section):
//
//	GET  /api/v2/groups/{group}/docs/tree                          → handleV2DocsTree
//	GET  /api/v2/groups/{group}/docs/page?path=...                 → handleV2DocsPage
//	GET  /api/v2/groups/{group}/docs/export?format=zip&kind=all    → handleV2DocsExport
//
// POST /api/v2/groups/{group}/docs/generate is intentionally NOT implemented.
// Doc generation is performed by the coding agent via the grafel docs
// skill, not by an HTTP endpoint or CLI command.

package dashboard

import (
	"archive/zip"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/cajasmota/grafel/internal/daemon"
)

// ── Wire shapes ────────────────────────────────────────────────────────────

// v2DocsTreeReply wraps the per-repo tree with a top-level flag that
// tells the UI whether the generate-docs skill has run for this group.
// When SkillGenerated is false, the tree may contain pre-existing repo
// README files, not skill output — the UI shows the onboarding CTA.
type v2DocsTreeReply struct {
	SkillGenerated bool        `json:"skillGenerated"`
	Nodes          []v2DocNode `json:"nodes"`
	// BusinessNodes holds the SEPARATE, non-per-repo business documentation
	// set (capabilities / domain / user-journeys / business-rules) when the
	// docs skill has produced it under a `business/` doc set. Empty when no
	// business docs exist — the UI then shows a business onboarding state.
	// See #1622 (chooser) + #1623 (business-docs skill).
	BusinessNodes []v2DocNode `json:"businessNodes"`
}

// v2DocNode is one node in the generated-docs file tree. It mirrors the
// DocNode TypeScript interface in data/types.ts.
//
//	dir  → "folder"   (repo root, modules/, reference/, patterns/, …)
//	file → "doc"      (a renderable .md document; Path is its API key)
type v2DocNode struct {
	Type       string      `json:"type"`                 // "folder" | "doc"
	Name       string      `json:"name"`                 // display label
	Path       string      `json:"path,omitempty"`       // doc key for /docs/page?path=  (docs only)
	Category   string      `json:"category,omitempty"`   // top-level section: overview|modules|reference|patterns|guide
	IsRepoDocs bool        `json:"isRepoDocs,omitempty"` // true = not skill-generated (raw repo markdown)
	Children   []v2DocNode `json:"children,omitempty"`
}

// v2DocPageReply is the data payload for a single rendered doc page.
type v2DocPageReply struct {
	Path     string `json:"path"`
	Title    string `json:"title"`
	Markdown string `json:"markdown"`
}

// ── Handlers ───────────────────────────────────────────────────────────────

// handleV2DocsTree — GET /api/v2/groups/{group}/docs/tree
//
// Returns the tree of GENERATED markdown documents for the Docs screen left
// pane, grouped per-repo then by doc category (overview / modules / reference
// / patterns / guides). The response includes a top-level skillGenerated flag
// so the UI can distinguish skill output from pre-existing repo READMEs.
// When no docs exist the response is {skillGenerated:false, nodes:[]}.
func (s *Server) handleV2DocsTree(w http.ResponseWriter, r *http.Request) {
	group := r.PathValue("group")
	if _, err := s.graphs.GetGroup(group); err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", "group not found: "+group)
		return
	}

	docPaths, err := groupDocPaths(group)
	if err != nil {
		// No registered docs path — not generated yet.
		writeV2JSON(w, http.StatusOK, v2OK(v2DocsTreeReply{SkillGenerated: false, Nodes: []v2DocNode{}}))
		return
	}

	roots := []v2DocNode{}
	businessRoots := []v2DocNode{}
	skillGenerated := false

	// Deterministic repo order.
	slugs := make([]string, 0, len(docPaths))
	for slug := range docPaths {
		slugs = append(slugs, slug)
	}
	sort.Strings(slugs)

	for _, slug := range slugs {
		docPath := docPaths[slug]
		if docPath == "" {
			continue
		}
		if _, err := os.Stat(docPath); err != nil {
			continue
		}
		isSkill := isSkillGeneratedDir(docPath)
		if isSkill {
			skillGenerated = true
		}
		// TECHNICAL tree: the per-repo doc tree, excluding the business/ set.
		repoNode := buildV2DocTree(docPath, slug)
		repoNode.IsRepoDocs = !isSkill
		if len(repoNode.Children) > 0 {
			roots = append(roots, repoNode)
		}
		// LEGACY: pre-#1624 business docs co-located under a repo's docs
		// dir (`<repo>/docs/business/`). Preserved for groups that haven't
		// migrated to the store layout yet.
		bizDir := filepath.Join(docPath, "business")
		if info, err := os.Stat(bizDir); err == nil && info.IsDir() {
			bizNode := buildV2BusinessTree(docPath, bizDir, slug)
			if len(bizNode.Children) > 0 {
				businessRoots = append(businessRoots, bizNode)
			}
		}
	}

	// BUSINESS tier (post-#1624): group-synthesised docs live at
	// `~/.grafel/docs/<group>/business/` independent of any repo. When
	// present, this is the authoritative source (overrides any legacy
	// per-repo `business/` fallback collected above).
	if bizDir := daemon.BusinessDocsDir(group); dirHasContent(bizDir) {
		skillGenerated = true
		bizNode := buildV2BusinessTreeFromStore(bizDir)
		if len(bizNode.Children) > 0 {
			businessRoots = []v2DocNode{bizNode}
		}
	}

	writeV2JSON(w, http.StatusOK, v2OK(v2DocsTreeReply{
		SkillGenerated: skillGenerated,
		Nodes:          roots,
		BusinessNodes:  businessRoots,
	}))
}

// handleV2DocsPage — GET /api/v2/groups/{group}/docs/page?path=<repoSlug/rel/path.md>
//
// Returns the raw markdown of a single generated doc document. The {path}
// query param is the doc key emitted in the tree (repoSlug + "/" + relPath).
func (s *Server) handleV2DocsPage(w http.ResponseWriter, r *http.Request) {
	group := r.PathValue("group")
	rawPath := r.URL.Query().Get("path")
	if rawPath == "" {
		writeV2Err(w, http.StatusBadRequest, "bad_request", "path query param required")
		return
	}
	if _, err := s.graphs.GetGroup(group); err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", "group not found: "+group)
		return
	}

	docPaths, err := groupDocPaths(group)
	if err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", err.Error())
		return
	}

	// rawPath is "<repoSlug>/<rel...>" — split off the repo slug.
	slash := strings.IndexByte(rawPath, '/')
	if slash < 0 {
		writeV2Err(w, http.StatusBadRequest, "bad_request", "malformed doc path")
		return
	}
	repoSlug := rawPath[:slash]
	rel := rawPath[slash+1:]

	var docPath string
	if repoSlug == "business" {
		// Group-level business docs from the store (post-#1624). The doc key
		// "business/<rel>" resolves under ~/.grafel/docs/<group>/business/.
		docPath = daemon.BusinessDocsDir(group)
		if !dirHasContent(docPath) {
			// Fall through to per-repo lookup (legacy business/ subdirs).
			docPath = ""
		}
	}
	if docPath == "" {
		var ok bool
		docPath, ok = docPaths[repoSlug]
		if !ok || docPath == "" {
			writeV2Err(w, http.StatusNotFound, "not_found", "unknown repo: "+repoSlug)
			return
		}
	}

	// Sanitize: prevent path traversal.
	clean := filepath.Clean("/" + rel)
	target := filepath.Join(docPath, clean)
	if !strings.HasPrefix(target, docPath) {
		writeV2Err(w, http.StatusBadRequest, "bad_request", "invalid path")
		return
	}
	data, err := os.ReadFile(target)
	if err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", "doc not found: "+rawPath)
		return
	}

	reply := v2DocPageReply{
		Path:     rawPath,
		Title:    docTitleFromMarkdown(string(data), filepath.Base(target)),
		Markdown: string(data),
	}
	writeV2JSON(w, http.StatusOK, v2OK(reply))
}

// ── Helpers ────────────────────────────────────────────────────────────────

// docCategory maps a doc's relative path to a top-level section label used to
// group + order documents within a repo.
func docCategory(rel string) (label, key string) {
	r := filepath.ToSlash(rel)
	switch {
	case r == "overview.md" || r == "README.md":
		return "Overview", "overview"
	case strings.HasPrefix(r, "modules/"):
		return "Modules", "modules"
	case strings.HasPrefix(r, "reference/"):
		return "Reference", "reference"
	case strings.HasPrefix(r, "patterns/"):
		return "Patterns", "patterns"
	default:
		return "Guides", "guide"
	}
}

// isSkillGeneratedDir reports whether a docs directory looks like it was
// produced by the grafel generate-docs skill. The skill always writes
// at least one of:
//   - docs/overview.md
//   - docs/modules/ (directory)
//
// Pre-existing repo READMEs never have this structure.
func isSkillGeneratedDir(docPath string) bool {
	if _, err := os.Stat(filepath.Join(docPath, "overview.md")); err == nil {
		return true
	}
	if info, err := os.Stat(filepath.Join(docPath, "modules")); err == nil && info.IsDir() {
		return true
	}
	return false
}

// categoryOrder gives a deterministic display order for doc sections.
func categoryOrder(key string) int {
	switch key {
	case "overview":
		return 0
	case "guide":
		return 1
	case "modules":
		return 2
	case "reference":
		return 3
	case "patterns":
		return 4
	default:
		return 9
	}
}

// buildV2DocTree walks a repo's docs directory and produces a category-grouped
// tree of renderable markdown documents. Only .md files become "doc" leaves;
// every leaf carries the API key (repoSlug + "/" + relPath) used by the page
// endpoint.
func buildV2DocTree(docRoot, repoSlug string) v2DocNode {
	// Collect every markdown file relative to docRoot, with its category.
	type docFile struct {
		rel     string
		catKey  string
		catName string
	}
	var files []docFile

	_ = filepath.Walk(docRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		name := info.Name()
		if strings.HasPrefix(name, ".") {
			return nil
		}
		if !strings.EqualFold(filepath.Ext(name), ".md") {
			return nil
		}
		rel, rerr := filepath.Rel(docRoot, path)
		if rerr != nil {
			return nil
		}
		relSlash := filepath.ToSlash(rel)
		// Skip enrichment frontmatter files — they back the graph surfaces,
		// not the human-readable docs portal.
		if strings.HasPrefix(relSlash, "enrichments/") {
			return nil
		}
		// Skip the business/ doc set — it is surfaced separately in the
		// Business documentation view, not the technical per-repo tree.
		if strings.HasPrefix(relSlash, "business/") {
			return nil
		}
		catName, catKey := docCategory(rel)
		files = append(files, docFile{rel: filepath.ToSlash(rel), catKey: catKey, catName: catName})
		return nil
	})

	// Group by category.
	byCat := map[string][]docFile{}
	catName := map[string]string{}
	for _, f := range files {
		byCat[f.catKey] = append(byCat[f.catKey], f)
		catName[f.catKey] = f.catName
	}

	cats := make([]string, 0, len(byCat))
	for k := range byCat {
		cats = append(cats, k)
	}
	sort.Slice(cats, func(i, j int) bool {
		oi, oj := categoryOrder(cats[i]), categoryOrder(cats[j])
		if oi != oj {
			return oi < oj
		}
		return cats[i] < cats[j]
	})

	repoNode := v2DocNode{Type: "folder", Name: repoSlug}
	for _, cat := range cats {
		group := byCat[cat]
		sort.Slice(group, func(i, j int) bool { return group[i].rel < group[j].rel })

		catNode := v2DocNode{Type: "folder", Name: catName[cat], Category: cat}
		for _, f := range group {
			catNode.Children = append(catNode.Children, v2DocNode{
				Type:     "doc",
				Name:     docLabel(f.rel),
				Path:     repoSlug + "/" + f.rel,
				Category: cat,
			})
		}
		repoNode.Children = append(repoNode.Children, catNode)
	}
	return repoNode
}

// buildV2BusinessTree walks the `business/` doc set under a repo and produces a
// flat per-repo node whose doc keys remain rooted at the repo docs dir
// (repoSlug + "/business/" + rel) so the page endpoint resolves them. Business
// docs are NOT grouped by the technical categories; they are listed by file.
func buildV2BusinessTree(docRoot, bizDir, repoSlug string) v2DocNode {
	type docFile struct{ rel string }
	var files []docFile

	_ = filepath.Walk(bizDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		name := info.Name()
		if strings.HasPrefix(name, ".") {
			return nil
		}
		if !strings.EqualFold(filepath.Ext(name), ".md") {
			return nil
		}
		// rel is rooted at docRoot so the key is "<slug>/business/<...>".
		rel, rerr := filepath.Rel(docRoot, path)
		if rerr != nil {
			return nil
		}
		files = append(files, docFile{rel: filepath.ToSlash(rel)})
		return nil
	})

	sort.Slice(files, func(i, j int) bool { return files[i].rel < files[j].rel })

	repoNode := v2DocNode{Type: "folder", Name: repoSlug}
	for _, f := range files {
		repoNode.Children = append(repoNode.Children, v2DocNode{
			Type: "doc",
			Name: docLabel(f.rel),
			Path: repoSlug + "/" + f.rel,
		})
	}
	return repoNode
}

// buildV2BusinessTreeFromStore walks the post-#1624 group-level business
// docs directory `~/.grafel/docs/<group>/business/`. Every doc key
// emitted is "business/<rel>" so the page handler routes it through the
// synthetic "business" slug.
func buildV2BusinessTreeFromStore(bizDir string) v2DocNode {
	var files []string
	_ = filepath.Walk(bizDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		name := info.Name()
		if strings.HasPrefix(name, ".") {
			return nil
		}
		if !strings.EqualFold(filepath.Ext(name), ".md") {
			return nil
		}
		rel, rerr := filepath.Rel(bizDir, path)
		if rerr != nil {
			return nil
		}
		files = append(files, filepath.ToSlash(rel))
		return nil
	})
	sort.Strings(files)

	node := v2DocNode{Type: "folder", Name: "business"}
	for _, rel := range files {
		node.Children = append(node.Children, v2DocNode{
			Type: "doc",
			Name: docLabel(rel),
			Path: "business/" + rel,
		})
	}
	return node
}

// handleV2DocsExport — GET /api/v2/groups/{group}/docs/export?format=zip&kind=all
//
// Streams an archive of the group's generated docs. The endpoint is designed
// to be extensible: callers select a `kind` (all | technical | business) and a
// `format` (zip; more formats can be added later). The response body is the
// archive itself; metadata travels in headers (Content-Type, filename).
//
// The default contract is `format=zip&kind=all`, which produces a zip whose
// top-level layout mirrors the store: `<group>/<repoSlug>/...` for technical
// docs and `<group>/business/...` for business docs.
func (s *Server) handleV2DocsExport(w http.ResponseWriter, r *http.Request) {
	group := r.PathValue("group")
	if _, err := s.graphs.GetGroup(group); err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", "group not found: "+group)
		return
	}

	format := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("format")))
	if format == "" {
		format = "zip"
	}
	if format != "zip" {
		writeV2Err(w, http.StatusBadRequest, "bad_request", "unsupported format: "+format+" (supported: zip)")
		return
	}

	kind := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("kind")))
	if kind == "" {
		kind = "all"
	}
	switch kind {
	case "all", "technical", "business":
	default:
		writeV2Err(w, http.StatusBadRequest, "bad_request", "unsupported kind: "+kind+" (supported: all, technical, business)")
		return
	}

	// Resolve sources from the canonical resolver so legacy `<repo>/docs/`
	// still exports until a group is fully migrated.
	docPaths, err := groupDocPaths(group)
	if err != nil {
		writeV2Err(w, http.StatusNotFound, "not_found", err.Error())
		return
	}

	// Collect (archive-prefix → on-disk root) pairs. The order is
	// deterministic so test fixtures and downloads stay stable.
	type src struct{ prefix, root string }
	var sources []src
	if kind == "all" || kind == "technical" {
		slugs := make([]string, 0, len(docPaths))
		for slug := range docPaths {
			slugs = append(slugs, slug)
		}
		sort.Strings(slugs)
		for _, slug := range slugs {
			root := docPaths[slug]
			if !dirHasContent(root) {
				continue
			}
			// Skip when this slug only resolved to a repo root with no
			// generated docs (defensive — keeps the archive clean).
			sources = append(sources, src{prefix: group + "/" + slug, root: root})
		}
	}
	if kind == "all" || kind == "business" {
		if bizDir := daemon.BusinessDocsDir(group); dirHasContent(bizDir) {
			sources = append(sources, src{prefix: group + "/business", root: bizDir})
		}
	}

	if len(sources) == 0 {
		writeV2Err(w, http.StatusNotFound, "not_found", "no docs to export for group: "+group)
		return
	}

	filename := fmt.Sprintf("%s-docs-%s.zip", group, time.Now().UTC().Format("20060102-150405"))
	w.Header().Set("Content-Type", "application/zip")
	w.Header().Set("Content-Disposition", `attachment; filename="`+filename+`"`)

	zw := zip.NewWriter(w)
	defer zw.Close()

	for _, s := range sources {
		if err := zipAddTree(zw, s.root, s.prefix); err != nil {
			// We've already started streaming the response — best-effort log
			// and abort. The client will see a truncated archive.
			return
		}
	}
}

// zipAddTree walks `root` and appends every regular file under it to `zw`
// with the archive path `prefix/<rel>`. Hidden files (.git, .DS_Store, …)
// are skipped so the export stays clean.
func zipAddTree(zw *zip.Writer, root, prefix string) error {
	return filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // skip unreadable entries rather than aborting the export
		}
		name := info.Name()
		if strings.HasPrefix(name, ".") {
			if info.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if info.IsDir() {
			return nil
		}
		rel, rerr := filepath.Rel(root, path)
		if rerr != nil {
			return nil
		}
		archivePath := prefix + "/" + filepath.ToSlash(rel)
		fh, herr := zip.FileInfoHeader(info)
		if herr != nil {
			return nil
		}
		fh.Name = archivePath
		fh.Method = zip.Deflate
		fwriter, werr := zw.CreateHeader(fh)
		if werr != nil {
			return werr
		}
		f, oerr := os.Open(path)
		if oerr != nil {
			return nil
		}
		_, _ = io.Copy(fwriter, f)
		_ = f.Close()
		return nil
	})
}

// docLabel produces a human-friendly label for a doc leaf from its rel path.
// e.g. "modules/order-service/README.md" → "order-service",
//
//	"reference/api.md" → "api", "overview.md" → "overview".
func docLabel(rel string) string {
	r := filepath.ToSlash(rel)
	base := filepath.Base(r)
	// For a directory README, label with the directory name instead.
	if strings.EqualFold(base, "README.md") {
		dir := filepath.Base(filepath.Dir(r))
		if dir != "." && dir != "" {
			return dir
		}
	}
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// docTitleFromMarkdown returns the first H1 in the markdown, falling back to
// the filename (sans extension) when no heading is present.
func docTitleFromMarkdown(md, fallbackBase string) string {
	for _, line := range strings.Split(md, "\n") {
		t := strings.TrimSpace(line)
		if strings.HasPrefix(t, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(t, "# "))
		}
	}
	return strings.TrimSuffix(fallbackBase, filepath.Ext(fallbackBase))
}
