// Package extractors imports all extractor sub-packages so their init()
// functions register with the global registry. This file is MANUALLY
// MAINTAINED — add a new blank import in alphabetical order when adding
// a new extractor. See REGISTRY_CODEGEN.md for details.
//
// Do NOT remove this file or its imports — the registry depends on
// side-effects from each sub-package's init().

package extractors

import (
	_ "github.com/cajasmota/grafel/internal/extractors/assembly"
	_ "github.com/cajasmota/grafel/internal/extractors/astro"
	_ "github.com/cajasmota/grafel/internal/extractors/avro"
	_ "github.com/cajasmota/grafel/internal/extractors/bicep"
	_ "github.com/cajasmota/grafel/internal/extractors/clojure"
	_ "github.com/cajasmota/grafel/internal/extractors/cobol"
	_ "github.com/cajasmota/grafel/internal/extractors/cpp"
	_ "github.com/cajasmota/grafel/internal/extractors/crystal"
	_ "github.com/cajasmota/grafel/internal/extractors/csharp"
	_ "github.com/cajasmota/grafel/internal/extractors/css"
	_ "github.com/cajasmota/grafel/internal/extractors/dart"
	_ "github.com/cajasmota/grafel/internal/extractors/dockerfile"
	_ "github.com/cajasmota/grafel/internal/extractors/elixir"
	_ "github.com/cajasmota/grafel/internal/extractors/elm"
	_ "github.com/cajasmota/grafel/internal/extractors/erlang"
	_ "github.com/cajasmota/grafel/internal/extractors/fish"
	_ "github.com/cajasmota/grafel/internal/extractors/fsharp"
	_ "github.com/cajasmota/grafel/internal/extractors/golang"
	_ "github.com/cajasmota/grafel/internal/extractors/graphql"
	_ "github.com/cajasmota/grafel/internal/extractors/groovy"
	_ "github.com/cajasmota/grafel/internal/extractors/haskell"
	_ "github.com/cajasmota/grafel/internal/extractors/hcl"
	_ "github.com/cajasmota/grafel/internal/extractors/html"
	_ "github.com/cajasmota/grafel/internal/extractors/idris"
	_ "github.com/cajasmota/grafel/internal/extractors/java"
	_ "github.com/cajasmota/grafel/internal/extractors/javascript"
	_ "github.com/cajasmota/grafel/internal/extractors/jcl"
	_ "github.com/cajasmota/grafel/internal/extractors/jsonschema"
	_ "github.com/cajasmota/grafel/internal/extractors/just"
	_ "github.com/cajasmota/grafel/internal/extractors/kotlin"
	_ "github.com/cajasmota/grafel/internal/extractors/lisp"
	_ "github.com/cajasmota/grafel/internal/extractors/lua"
	_ "github.com/cajasmota/grafel/internal/extractors/markdown"
	_ "github.com/cajasmota/grafel/internal/extractors/nim"
	_ "github.com/cajasmota/grafel/internal/extractors/ocaml"
	_ "github.com/cajasmota/grafel/internal/extractors/php"
	_ "github.com/cajasmota/grafel/internal/extractors/pony"
	_ "github.com/cajasmota/grafel/internal/extractors/proto"
	_ "github.com/cajasmota/grafel/internal/extractors/python"
	_ "github.com/cajasmota/grafel/internal/extractors/razor"
	_ "github.com/cajasmota/grafel/internal/extractors/reasonml"
	_ "github.com/cajasmota/grafel/internal/extractors/rescript"
	_ "github.com/cajasmota/grafel/internal/extractors/ruby"
	_ "github.com/cajasmota/grafel/internal/extractors/rust"
	_ "github.com/cajasmota/grafel/internal/extractors/scala"
	_ "github.com/cajasmota/grafel/internal/extractors/shell"
	_ "github.com/cajasmota/grafel/internal/extractors/sml"
	_ "github.com/cajasmota/grafel/internal/extractors/solidity"
	_ "github.com/cajasmota/grafel/internal/extractors/sql"
	_ "github.com/cajasmota/grafel/internal/extractors/svelte"
	_ "github.com/cajasmota/grafel/internal/extractors/swift"
	_ "github.com/cajasmota/grafel/internal/extractors/verilog"
	_ "github.com/cajasmota/grafel/internal/extractors/vhdl"
	_ "github.com/cajasmota/grafel/internal/extractors/vue"
	_ "github.com/cajasmota/grafel/internal/extractors/yaml"
	_ "github.com/cajasmota/grafel/internal/extractors/zig"
)
