package rust

import (
	"context"
	"regexp"
	"strings"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	"github.com/cajasmota/grafel/internal/extractor"
	"github.com/cajasmota/grafel/internal/types"
)

// tonic is a gRPC framework for Rust. A gRPC service is implemented by writing
// an `impl <Service> for <Type>` block (the trait is generated by `tonic-build`
// from the .proto) annotated with `#[tonic::async_trait]`. Each async method is
// a unary/streaming RPC whose request and response types are wrapped in
// `Request<T>` / `Response<T>`:
//
//	#[tonic::async_trait]
//	impl Greeter for MyGreeter {
//	    async fn say_hello(
//	        &self,
//	        request: Request<HelloRequest>,
//	    ) -> Result<Response<HelloReply>, Status> { ... }
//	}
//
//	Server::builder()
//	    .add_service(GreeterServer::new(MyGreeter::default()))
//	    .serve(addr).await?;
//
// Each RPC method maps to a synthetic endpoint with verb RPC and the canonical
// gRPC path /<Service>/<Method>. The request/response message types are emitted
// as SCOPE.Schema DTO references. `.add_service(<Svc>Server::new(...))` is the
// service-registration site.
//
// HONEST LIMIT: the proto-generated server trait + message structs live in code
// emitted by `tonic-build` in build.rs (e.g. OUT_DIR/*.rs), which is not
// statically present in the source tree. We recover the service name, method
// names, and request/response message *names* from the hand-written `impl`
// block and from `<Svc>Server::new` registrations; full message field shapes
// (defined in the generated structs) are not statically resolvable here.

func init() {
	extractor.Register("custom_rust_tonic", &tonicExtractor{})
}

type tonicExtractor struct{}

func (e *tonicExtractor) Language() string { return "custom_rust_tonic" }

var (
	// `#[tonic::async_trait]` (or a bare `#[async_trait]` next to a gRPC impl)
	// preceding `impl <Service> for <Type>`. Capture group 1 = service trait
	// name, group 2 = implementing type.
	reTonicServiceImpl = regexp.MustCompile(
		`#\[(?:tonic::)?async_trait\]\s*(?:#\[[^\]]*\]\s*)*impl\s+(?:<[^>]*>\s*)?([A-Za-z_]\w*)\s+for\s+([A-Za-z_]\w*)`,
	)
	// An RPC method inside the service impl. Captures the method name (1) and
	// the Request<T> message type (2). Tolerates an arg name before the colon
	// and a leading `&self,`.
	reTonicRpcMethod = regexp.MustCompile(
		`async\s+fn\s+([A-Za-z_]\w*)\s*\(\s*&self\s*,\s*(?:[A-Za-z_]\w*\s*:\s*)?(?:tonic::)?Request\s*<\s*([A-Za-z_]\w*)`,
	)
	// The Response<T> return message type for an RPC. Captured per method body
	// by scanning the method signature.
	reTonicResponse = regexp.MustCompile(
		`Result\s*<\s*(?:tonic::)?Response\s*<\s*([A-Za-z_]\w*)`,
	)
	// `.add_service(GreeterServer::new(...))` — service registration. Capture
	// group 1 = the generated server type (e.g. GreeterServer).
	reTonicAddService = regexp.MustCompile(
		`\.add_service\s*\(\s*(?:[A-Za-z_]\w*\s*::\s*)*([A-Za-z_]\w*Server)\s*::\s*new`,
	)
)

func (e *tonicExtractor) Extract(ctx context.Context, file extractor.FileInput) ([]types.EntityRecord, error) {
	tracer := otel.Tracer("grafel/custom/rust")
	_, span := tracer.Start(ctx, "indexer.tonic_extractor.extract",
		trace.WithAttributes(
			attribute.String("language", file.Language),
			attribute.String("framework", "tonic"),
			attribute.String("file_path", file.Path),
		),
	)
	defer span.End()

	if len(file.Content) == 0 || file.Language != "rust" {
		return nil, nil
	}

	src := string(file.Content)

	// File-signal gate: require a tonic marker so the extractor is a no-op on
	// non-gRPC Rust files.
	if !strings.Contains(src, "async_trait") &&
		!strings.Contains(src, "add_service") &&
		!strings.Contains(src, "tonic") {
		return nil, nil
	}

	var entities []types.EntityRecord
	seen := make(map[string]bool)
	add := func(ent types.EntityRecord) {
		key := ent.Kind + ":" + ent.Name
		if seen[key] {
			return
		}
		seen[key] = true
		entities = append(entities, ent)
	}

	// 1. #[tonic::async_trait] impl <Service> for <Type> -> one RPC endpoint
	//    per async method, path /<Service>/<Method>.
	for _, m := range reTonicServiceImpl.FindAllStringSubmatchIndex(src, -1) {
		service := src[m[2]:m[3]]
		implType := src[m[4]:m[5]]
		bodyStart, bodyEnd := tonicBlockBody(src, m[1])
		if bodyStart < 0 {
			continue
		}
		body := src[bodyStart:bodyEnd]

		for _, rm := range reTonicRpcMethod.FindAllStringSubmatchIndex(body, -1) {
			method := body[rm[2]:rm[3]]
			reqType := body[rm[4]:rm[5]]
			methodOff := bodyStart + rm[0]

			// Find the Response<T> type within this method signature (scan from
			// the method start to the next `{`).
			respType := tonicResponseType(body, rm[0])

			path := "/" + service + "/" + method
			name := "RPC " + path
			ent := makeEntity(name, "SCOPE.Operation", "endpoint", file.Path, file.Language, lineOf(src, methodOff))
			setProps(&ent, "framework", "tonic",
				"provenance", "INFERRED_FROM_TONIC_RPC",
				"http_method", "RPC", "verb", "RPC",
				"route_path", path, "rpc_protocol", "grpc",
				"grpc_service", service, "grpc_method", method,
				"impl_type", implType,
				"request_message", reqType, "handler_name", implType+"."+method)
			if respType != "" {
				setProps(&ent, "response_message", respType)
			}
			add(ent)

			// Emit request/response message DTO references.
			tonicAddDTO(add, reqType, "request", file, lineOf(src, methodOff))
			if respType != "" {
				tonicAddDTO(add, respType, "response", file, lineOf(src, methodOff))
			}
		}
	}

	// 2. .add_service(<Svc>Server::new(...)) -> SCOPE.Service registration.
	for _, m := range reTonicAddService.FindAllStringSubmatchIndex(src, -1) {
		serverType := src[m[2]:m[3]]
		service := strings.TrimSuffix(serverType, "Server")
		ent := makeEntity("grpc_service:"+serverType, "SCOPE.Service", "grpc_service", file.Path, file.Language, lineOf(src, m[0]))
		setProps(&ent, "framework", "tonic",
			"provenance", "INFERRED_FROM_TONIC_ADD_SERVICE",
			"server_type", serverType, "grpc_service", service)
		add(ent)
	}

	span.SetAttributes(attribute.Int("entity_count", len(entities)))
	return entities, nil
}

// tonicAddDTO emits a SCOPE.Schema DTO reference for a gRPC message type.
func tonicAddDTO(add func(types.EntityRecord), msg, role string, file extractor.FileInput, line int) {
	if msg == "" {
		return
	}
	ent := makeEntity("grpc_dto:"+msg, "SCOPE.Schema", "dto", file.Path, file.Language, line)
	setProps(&ent, "framework", "tonic",
		"provenance", "INFERRED_FROM_TONIC_MESSAGE",
		"dto_name", msg, "grpc_message_role", role, "rpc_protocol", "grpc")
	add(ent)
}

// tonicResponseType scans forward from a method-start offset (within body) to
// the opening brace of the method body and returns the Response<T> message
// type, or "" when none is found before the body opens.
func tonicResponseType(body string, methodStart int) string {
	open := strings.IndexByte(body[methodStart:], '{')
	end := len(body)
	if open >= 0 {
		end = methodStart + open
	}
	sig := body[methodStart:end]
	if rm := reTonicResponse.FindStringSubmatch(sig); rm != nil {
		return rm[1]
	}
	return ""
}

// tonicBlockBody returns the byte range [start,end) of the impl block body
// beginning at the `{` that follows implHeaderEnd. Brace-balanced.
func tonicBlockBody(src string, implHeaderEnd int) (int, int) {
	open := strings.IndexByte(src[implHeaderEnd:], '{')
	if open < 0 {
		return -1, -1
	}
	open += implHeaderEnd
	depth := 0
	for i := open; i < len(src); i++ {
		switch src[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return open + 1, i
			}
		}
	}
	return -1, -1
}
