// persistence.go — Dart persistence / ORM model → table/column/collection
// schema synthesis (#5361, low-ranked-language epic #5360).
//
// Dart's mobile/Flutter ecosystem ships several embedded-database libraries.
// Before this extractor, zero Dart ORMs were tracked. This pass adds the four
// canonical persistence libraries (plus an honest-partial for raw sqflite SQL),
// mirroring the Crystal ORM shape (internal/custom/crystal/avram_orm.go) —
// SCOPE.Schema entities carrying framework + provenance props:
//
//   - drift  — annotation/class ORM. `class Foos extends Table { IntColumn get
//     id => integer()...; }` → table + typed columns. `@DriftDatabase(tables:
//     [Foos])` → a database SCOPE.Schema node.
//   - floor  — Room-inspired annotation ORM. `@entity class User { ... }` with
//     `@PrimaryKey` / `@ColumnInfo` fields → model + columns; `@dao` /
//     `@Database` carried as schema nodes.
//   - isar   — NoSQL embedded. `@collection class User { ... }` → a collection
//     model; `Id id;` and `@Index()`-decorated fields → columns.
//   - hive   — key/value typed boxes. `@HiveType(typeId: n) class User { ... }`
//     with `@HiveField(k)` → model + ordered fields.
//   - sqflite (honest-partial) — raw-SQL driver. `db.execute('CREATE TABLE
//     foos (id INTEGER PRIMARY KEY, name TEXT)')` → table + columns parsed from
//     the DDL. Query attribution / migrations are deferred.
//   - objectbox — `@Entity() class User { @Id() int id; }` → model + columns.
//
// Codegen awareness (#5361 item 4): freezed (`@freezed`) and json_serializable
// (`@JsonSerializable()`) annotations plus `part 'x.g.dart';` / `part
// 'x.freezed.dart';` directives are stamped onto the host model entity
// (codegen=freezed|json_serializable, has_part_g=true) so the graph records
// that the persisted/serialised shape is generated by build_runner.
//
// Honest exclusions / follow-ups (no fabricated schema):
//   - Query DSL attribution (drift `select(table)`, isar `.filter()`), DAO
//     method-level query parsing, migrations, and transactions are deferred.
//   - sqflite is raw-SQL only: non-`CREATE TABLE` statements are not modelled.
//
// Registration key: "custom_dart_persistence" (auto-dispatched for dart files
// via the `custom_dart_` prefix in custom_dispatch.go).
package dart

import (
	"context"
	"regexp"
	"strings"

	"github.com/cajasmota/grafel/internal/extractor"
	"github.com/cajasmota/grafel/internal/types"
)

func init() {
	extractor.Register("custom_dart_persistence", &persistenceExtractor{})
}

type persistenceExtractor struct{}

func (e *persistenceExtractor) Language() string { return "custom_dart_persistence" }

// ---------------------------------------------------------------------------
// Regexes
// ---------------------------------------------------------------------------

var (
	// drift — `class Foos extends Table {`. Group 1 = class (table) name.
	driftTableRe = regexp.MustCompile(
		`(?m)^[ \t]*(?:abstract\s+)?class\s+([A-Z]\w*)\s+extends\s+Table\b`)

	// drift typed column getter:
	//   `IntColumn get id => integer().autoIncrement()();`
	//   `TextColumn get name => text().withLength(min: 1)();`
	// Group 1 = Dart column type (IntColumn/TextColumn/...), 2 = field name,
	// 3 = the builder root (integer/text/boolean/real/dateTime/blob).
	driftColumnRe = regexp.MustCompile(
		`(?m)^[ \t]*([A-Za-z]+Column(?:<[^>]*>)?)\s+get\s+(\w+)\s*=>\s*([A-Za-z]+)\s*\(`)

	// drift database: `@DriftDatabase(tables: [Foos, Bars])`. Group 1 = the
	// raw table list. The annotated class name follows on a later line.
	driftDatabaseRe = regexp.MustCompile(
		`@DriftDatabase\s*\(\s*tables:\s*\[([^\]]*)\]`)

	// floor — `@entity` / `@Entity` preceding `class User {`. The bare /
	// no-parens form is floor's idiom; the parenthesised `@Entity()` form is
	// objectbox's (handled by objectboxEntityRe), so a `(` immediately after
	// the annotation is rejected here via the trailing `(?:\b|\s)` + negative
	// look — Go's RE2 has no lookahead, so we forbid a following `(` by
	// requiring the next char (if any on the line) not be `(`.
	floorEntityRe = regexp.MustCompile(
		`(?m)@[eE]ntity(?:\s|$)[^\n]*\n(?:[ \t]*@?\w[^\n]*\n)*?[ \t]*class\s+([A-Z]\w*)`)

	// floor — `@dao` / `@Dao` abstract class, and `@Database(...)` class.
	floorDaoRe = regexp.MustCompile(
		`(?m)@[dD]ao\b[^\n]*\n(?:[ \t]*@?\w[^\n]*\n)*?[ \t]*abstract\s+class\s+([A-Z]\w*)`)
	floorDatabaseRe = regexp.MustCompile(
		`(?m)@Database\s*\([^)]*\)[^\n]*\n(?:[ \t]*@?\w[^\n]*\n)*?[ \t]*abstract\s+class\s+([A-Z]\w*)`)

	// isar — `@collection` / `@Collection()` preceding `class User {`.
	isarCollectionRe = regexp.MustCompile(
		`(?m)@[cC]ollection(?:\(\))?\b[^\n]*\n(?:[ \t]*@?\w[^\n]*\n)*?[ \t]*class\s+([A-Z]\w*)`)

	// hive — `@HiveType(typeId: 0)` preceding `class User {`. Group 1 = the
	// typeId arg run, group 2 supplied by a follow-up class match.
	hiveTypeRe = regexp.MustCompile(
		`(?m)@HiveType\s*\(([^)]*)\)[^\n]*\n(?:[ \t]*@?\w[^\n]*\n)*?[ \t]*class\s+([A-Z]\w*)`)

	// objectbox — `@Entity()` (parenthesised, distinguishes from floor's bare
	// `@entity`) preceding `class User {`.
	objectboxEntityRe = regexp.MustCompile(
		`(?m)@Entity\s*\(\s*\)[^\n]*\n(?:[ \t]*@?\w[^\n]*\n)*?[ \t]*class\s+([A-Z]\w*)`)

	// Generic Dart field inside a model body: `final String name;`,
	// `int? age;`, `late String email;`, `String name = '';`. Group 1 = type,
	// group 2 = field name. Static / getters excluded by anchoring.
	dartFieldRe = regexp.MustCompile(
		`(?m)^[ \t]*(?:@\w+(?:\([^)]*\))?\s+)*(?:final\s+|late\s+|const\s+)*([A-Za-z_][\w<>]*\??)\s+(\w+)\s*(?:=|;)`)

	// hive field annotation marker on the immediately-following field:
	// `@HiveField(0) final String name;`. Group 1 = index.
	hiveFieldRe = regexp.MustCompile(
		`(?m)@HiveField\s*\(\s*(\d+)`)

	// sqflite raw DDL: `CREATE TABLE [IF NOT EXISTS] foos ( ... )`. Group 1 =
	// table name, group 2 = the column body.
	sqfliteCreateRe = regexp.MustCompile(
		`(?is)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?["'` + "`" + `]?(\w+)["'` + "`" + `]?\s*\(([^;]*?)\)\s*['"` + "`" + `]?\s*\)?\s*;`)

	// codegen markers.
	freezedRe    = regexp.MustCompile(`@[fF]reezed\b`)
	jsonSerialRe = regexp.MustCompile(`@JsonSerializable\s*\(`)
	partGRe      = regexp.MustCompile(`(?m)^[ \t]*part\s+'[^']*\.(g|freezed)\.dart'`)
)

// ---------------------------------------------------------------------------
// Pre-filter signals
// ---------------------------------------------------------------------------

// hasPersistenceSignal is a fast pre-filter: the file must reference at least
// one supported persistence library so we never misfire on plain classes.
func hasPersistenceSignal(content string) bool {
	for _, s := range []string{
		"extends Table", "DriftDatabase", "package:drift",
		"@entity", "@Entity", "package:floor",
		"@collection", "@Collection", "package:isar",
		"@HiveType", "package:hive",
		"package:objectbox",
		"CREATE TABLE", "package:sqflite", "openDatabase(",
	} {
		if strings.Contains(content, s) {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// Extract
// ---------------------------------------------------------------------------

func (e *persistenceExtractor) Extract(
	ctx context.Context,
	file extractor.FileInput,
) ([]types.EntityRecord, error) {
	if len(file.Content) == 0 || file.Language != "dart" {
		return nil, nil
	}
	src := string(file.Content)
	if !hasPersistenceSignal(src) {
		return nil, nil
	}

	codegen := detectCodegen(src)

	var out []types.EntityRecord
	out = append(out, extractDrift(src, file.Path, codegen)...)
	out = append(out, extractFloor(src, file.Path, codegen)...)
	out = append(out, extractIsar(src, file.Path, codegen)...)
	out = append(out, extractHive(src, file.Path, codegen)...)
	out = append(out, extractObjectbox(src, file.Path, codegen)...)
	out = append(out, extractSqflite(src, file.Path)...)
	return out, nil
}

// codegenInfo records the codegen markers found in a file.
type codegenInfo struct {
	freezed    bool
	jsonSerial bool
	hasPartG   bool
}

func detectCodegen(src string) codegenInfo {
	return codegenInfo{
		freezed:    freezedRe.MatchString(src),
		jsonSerial: jsonSerialRe.MatchString(src),
		hasPartG:   partGRe.MatchString(src),
	}
}

// stampCodegen attaches codegen-source provenance to a model entity.
func stampCodegen(e *types.EntityRecord, cg codegenInfo) {
	var parts []string
	if cg.freezed {
		parts = append(parts, "freezed")
	}
	if cg.jsonSerial {
		parts = append(parts, "json_serializable")
	}
	if len(parts) > 0 {
		e.Properties["codegen"] = strings.Join(parts, ",")
		e.Properties["build_runner"] = "true"
	}
	if cg.hasPartG {
		e.Properties["has_part_g"] = "true"
	}
}

// ---------------------------------------------------------------------------
// Shared schema builder
// ---------------------------------------------------------------------------

// newDartSchema builds a SCOPE.Schema entity stamped with the given Dart
// persistence framework + provenance. Subtype grain: model/table/column/
// collection/database/dao/association.
func newDartSchema(name, subtype, framework, path string, line int, provenance string) types.EntityRecord {
	e := types.EntityRecord{
		Name:       name,
		Kind:       "SCOPE.Schema",
		Subtype:    subtype,
		SourceFile: path,
		Language:   "dart",
		StartLine:  line,
		EndLine:    line,
		Properties: map[string]string{
			"framework":  framework,
			"provenance": provenance,
		},
	}
	return e
}

func lineAt(src string, byteOff int) int {
	return strings.Count(src[:byteOff], "\n") + 1
}

// ---------------------------------------------------------------------------
// drift
// ---------------------------------------------------------------------------

func extractDrift(src, path string, cg codegenInfo) []types.EntityRecord {
	var out []types.EntityRecord
	for _, m := range driftTableRe.FindAllStringSubmatchIndex(src, -1) {
		name := src[m[2]:m[3]]
		line := lineAt(src, m[0])
		bodyEnd := findBraceEndByte(src, m[1]+indexBrace(src[m[1]:]))
		bodyStart := m[1]
		body := ""
		if bodyStart < bodyEnd && bodyEnd <= len(src) {
			body = src[bodyStart:bodyEnd]
		}

		table := newDartSchema(name, "table", "drift", path, line,
			"INFERRED_FROM_DRIFT_TABLE")
		stampCodegen(&table, cg)
		table.Properties["orm"] = "drift"
		table.ID = table.ComputeID()
		out = append(out, table)

		for _, c := range driftColumnRe.FindAllStringSubmatchIndex(body, -1) {
			colName := body[c[4]:c[5]]
			colType := body[c[2]:c[3]]
			builder := body[c[6]:c[7]]
			cline := line + strings.Count(body[:c[0]], "\n")
			col := newDartSchema(colName, "column", "drift", path, cline,
				"INFERRED_FROM_DRIFT_COLUMN")
			col.Properties["column_type"] = colType
			col.Properties["sql_type"] = driftSQLType(builder)
			col.Properties["model"] = name
			if strings.Contains(body[c[1]:minInt(c[1]+120, len(body))], "autoIncrement") {
				col.Properties["primary_key"] = "true"
			}
			col.ID = col.ComputeID()
			out = append(out, col)
		}
	}

	// @DriftDatabase(tables: [...]) → database node + REFERENCES edges.
	for _, m := range driftDatabaseRe.FindAllStringSubmatchIndex(src, -1) {
		list := src[m[2]:m[3]]
		line := lineAt(src, m[0])
		// The annotated class name is the first `class X` after the annotation.
		dbName := "DriftDatabase"
		tail := src[m[1]:]
		if cm := regexp.MustCompile(`class\s+([A-Z]\w*)`).FindStringSubmatch(tail); cm != nil {
			dbName = cm[1]
		}
		db := newDartSchema(dbName, "database", "drift", path, line,
			"INFERRED_FROM_DRIFT_DATABASE")
		db.Properties["orm"] = "drift"
		for _, t := range splitList(list) {
			db.Relationships = append(db.Relationships, types.RelationshipRecord{
				ToID: t,
				Kind: "REFERENCES",
				Properties: map[string]string{
					"to_model": t,
					"ref_kind": "drift_table",
				},
			})
		}
		db.ID = db.ComputeID()
		out = append(out, db)
	}
	return out
}

// driftSQLType maps a drift column builder root to its SQL type.
func driftSQLType(builder string) string {
	switch builder {
	case "integer", "int64":
		return "INTEGER"
	case "text":
		return "TEXT"
	case "boolean":
		return "BOOLEAN"
	case "real":
		return "REAL"
	case "dateTime":
		return "DATETIME"
	case "blob":
		return "BLOB"
	}
	return builder
}

// ---------------------------------------------------------------------------
// floor
// ---------------------------------------------------------------------------

func extractFloor(src, path string, cg codegenInfo) []types.EntityRecord {
	var out []types.EntityRecord
	for _, m := range floorEntityRe.FindAllStringSubmatchIndex(src, -1) {
		name := src[m[2]:m[3]]
		line := lineAt(src, m[0])
		model := newDartSchema(name, "model", "floor", path, line,
			"INFERRED_FROM_FLOOR_ENTITY")
		model.Properties["orm"] = "floor"
		stampCodegen(&model, cg)
		model.ID = model.ComputeID()
		out = append(out, model)
		out = append(out, classFieldColumns(src, m[3], name, "floor",
			"INFERRED_FROM_FLOOR_COLUMN", path, line)...)
	}
	for _, m := range floorDaoRe.FindAllStringSubmatchIndex(src, -1) {
		name := src[m[2]:m[3]]
		dao := newDartSchema(name, "dao", "floor", path, lineAt(src, m[0]),
			"INFERRED_FROM_FLOOR_DAO")
		dao.Properties["orm"] = "floor"
		dao.ID = dao.ComputeID()
		out = append(out, dao)
	}
	for _, m := range floorDatabaseRe.FindAllStringSubmatchIndex(src, -1) {
		name := src[m[2]:m[3]]
		db := newDartSchema(name, "database", "floor", path, lineAt(src, m[0]),
			"INFERRED_FROM_FLOOR_DATABASE")
		db.Properties["orm"] = "floor"
		db.ID = db.ComputeID()
		out = append(out, db)
	}
	return out
}

// ---------------------------------------------------------------------------
// isar
// ---------------------------------------------------------------------------

func extractIsar(src, path string, cg codegenInfo) []types.EntityRecord {
	var out []types.EntityRecord
	for _, m := range isarCollectionRe.FindAllStringSubmatchIndex(src, -1) {
		name := src[m[2]:m[3]]
		line := lineAt(src, m[0])
		model := newDartSchema(name, "collection", "isar", path, line,
			"INFERRED_FROM_ISAR_COLLECTION")
		model.Properties["orm"] = "isar"
		model.Properties["store_kind"] = "nosql_embedded"
		stampCodegen(&model, cg)
		model.ID = model.ComputeID()
		out = append(out, model)
		cols := classFieldColumns(src, m[3], name, "isar",
			"INFERRED_FROM_ISAR_FIELD", path, line)
		// Stamp the `Id id` / `late Id id` field as primary key.
		for i := range cols {
			if cols[i].Properties["column_type"] == "Id" || cols[i].Name == "id" {
				cols[i].Properties["primary_key"] = "true"
				cols[i].ID = cols[i].ComputeID()
			}
		}
		out = append(out, cols...)
	}
	return out
}

// ---------------------------------------------------------------------------
// hive
// ---------------------------------------------------------------------------

func extractHive(src, path string, cg codegenInfo) []types.EntityRecord {
	var out []types.EntityRecord
	for _, m := range hiveTypeRe.FindAllStringSubmatchIndex(src, -1) {
		typeIDArg := strings.TrimSpace(src[m[2]:m[3]])
		name := src[m[4]:m[5]]
		line := lineAt(src, m[0])
		model := newDartSchema(name, "model", "hive", path, line,
			"INFERRED_FROM_HIVE_TYPE")
		model.Properties["orm"] = "hive"
		model.Properties["store_kind"] = "key_value"
		if typeIDArg != "" {
			model.Properties["type_id"] = strings.TrimSpace(strings.TrimPrefix(typeIDArg, "typeId:"))
		}
		stampCodegen(&model, cg)
		model.ID = model.ComputeID()
		out = append(out, model)

		// hive fields carry a @HiveField(n) ordinal — parse the class body.
		bodyStart := m[5]
		bodyEnd := findBraceEndByte(src, bodyStart+indexBrace(src[bodyStart:]))
		if bodyStart < bodyEnd && bodyEnd <= len(src) {
			body := src[bodyStart:bodyEnd]
			fieldIdx := hiveFieldRe.FindAllStringSubmatchIndex(body, -1)
			fields := dartFieldRe.FindAllStringSubmatchIndex(body, -1)
			for _, f := range fields {
				colName := body[f[4]:f[5]]
				colType := strings.TrimSuffix(body[f[2]:f[3]], "?")
				cline := line + strings.Count(body[:f[0]], "\n")
				col := newDartSchema(colName, "field", "hive", path, cline,
					"INFERRED_FROM_HIVE_FIELD")
				col.Properties["column_type"] = colType
				col.Properties["model"] = name
				// Match the nearest preceding @HiveField ordinal. Anchor on the
				// field NAME offset (f[4]) — dartFieldRe consumes any leading
				// `@HiveField(n)` annotation so f[0] sits AT that annotation,
				// which would make every field bind to the wrong (earlier)
				// ordinal.
				if ord := nearestHiveOrdinal(body, fieldIdx, f[4]); ord != "" {
					col.Properties["hive_field"] = ord
				}
				col.ID = col.ComputeID()
				out = append(out, col)
			}
		}
	}
	return out
}

// nearestHiveOrdinal returns the @HiveField index whose match immediately
// precedes the field at fieldOff, or "" when none.
func nearestHiveOrdinal(body string, hiveIdx [][]int, fieldOff int) string {
	best := ""
	bestPos := -1
	for _, h := range hiveIdx {
		if h[0] < fieldOff && h[0] > bestPos {
			bestPos = h[0]
			best = body[h[2]:h[3]]
		}
	}
	return best
}

// ---------------------------------------------------------------------------
// objectbox
// ---------------------------------------------------------------------------

func extractObjectbox(src, path string, cg codegenInfo) []types.EntityRecord {
	var out []types.EntityRecord
	for _, m := range objectboxEntityRe.FindAllStringSubmatchIndex(src, -1) {
		name := src[m[2]:m[3]]
		line := lineAt(src, m[0])
		model := newDartSchema(name, "model", "objectbox", path, line,
			"INFERRED_FROM_OBJECTBOX_ENTITY")
		model.Properties["orm"] = "objectbox"
		model.Properties["store_kind"] = "nosql_embedded"
		stampCodegen(&model, cg)
		model.ID = model.ComputeID()
		out = append(out, model)
		cols := classFieldColumns(src, m[3], name, "objectbox",
			"INFERRED_FROM_OBJECTBOX_FIELD", path, line)
		for i := range cols {
			if cols[i].Name == "id" {
				cols[i].Properties["primary_key"] = "true"
				cols[i].ID = cols[i].ComputeID()
			}
		}
		out = append(out, cols...)
	}
	return out
}

// ---------------------------------------------------------------------------
// sqflite (raw SQL, honest-partial)
// ---------------------------------------------------------------------------

func extractSqflite(src, path string) []types.EntityRecord {
	var out []types.EntityRecord
	for _, m := range sqfliteCreateRe.FindAllStringSubmatchIndex(src, -1) {
		table := src[m[2]:m[3]]
		colBody := src[m[4]:m[5]]
		line := lineAt(src, m[0])
		t := newDartSchema(table, "table", "sqflite", path, line,
			"INFERRED_FROM_SQFLITE_DDL")
		t.Properties["orm"] = "sqflite"
		t.Properties["raw_sql"] = "true"
		t.ID = t.ComputeID()
		out = append(out, t)
		for _, c := range parseSQLColumns(colBody) {
			col := newDartSchema(c.name, "column", "sqflite", path, line,
				"INFERRED_FROM_SQFLITE_DDL")
			col.Properties["sql_type"] = c.typ
			col.Properties["model"] = table
			if c.primary {
				col.Properties["primary_key"] = "true"
			}
			col.ID = col.ComputeID()
			out = append(out, col)
		}
	}
	return out
}

type sqlColumn struct {
	name    string
	typ     string
	primary bool
}

// parseSQLColumns splits a CREATE TABLE column body into column defs. Best-
// effort: skips table-level constraint clauses (PRIMARY KEY (...), FOREIGN
// KEY, UNIQUE(...)) that have no leading column name.
func parseSQLColumns(body string) []sqlColumn {
	var out []sqlColumn
	for _, raw := range splitTopLevel(body) {
		f := strings.Fields(strings.TrimSpace(raw))
		if len(f) < 1 {
			continue
		}
		head := strings.ToUpper(f[0])
		// Skip table-level constraint lines.
		if head == "PRIMARY" || head == "FOREIGN" || head == "UNIQUE" ||
			head == "CHECK" || head == "CONSTRAINT" {
			continue
		}
		name := strings.Trim(f[0], "\"'`")
		typ := ""
		if len(f) >= 2 {
			typ = strings.ToUpper(f[1])
		}
		primary := strings.Contains(strings.ToUpper(raw), "PRIMARY KEY")
		out = append(out, sqlColumn{name: name, typ: typ, primary: primary})
	}
	return out
}

// splitTopLevel splits on commas that are not nested inside parentheses.
func splitTopLevel(s string) []string {
	var out []string
	depth := 0
	start := 0
	for i, r := range s {
		switch r {
		case '(':
			depth++
		case ')':
			depth--
		case ',':
			if depth == 0 {
				out = append(out, s[start:i])
				start = i + 1
			}
		}
	}
	out = append(out, s[start:])
	return out
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

// classFieldColumns parses the brace-balanced body of the class whose head ends
// at headEnd and emits a SCOPE.Schema/column per Dart field declaration.
func classFieldColumns(src string, headEnd int, model, framework, provenance, path string, modelLine int) []types.EntityRecord {
	open := headEnd + indexBrace(src[headEnd:])
	if open < headEnd || open >= len(src) {
		return nil
	}
	end := findBraceEndByte(src, open)
	if open+1 > end || end > len(src) {
		return nil
	}
	body := src[open+1 : end]
	var out []types.EntityRecord
	seen := map[string]bool{}
	for _, f := range dartFieldRe.FindAllStringSubmatchIndex(body, -1) {
		colType := strings.TrimSuffix(body[f[2]:f[3]], "?")
		colName := body[f[4]:f[5]]
		if seen[colName] || isDartFieldKeyword(colType) {
			continue
		}
		seen[colName] = true
		cline := modelLine + strings.Count(body[:f[0]], "\n")
		col := newDartSchema(colName, "column", framework, path, cline, provenance)
		col.ID = col.ComputeID()
		col.Properties["column_type"] = colType
		col.Properties["model"] = model
		out = append(out, col)
	}
	return out
}

// isDartFieldKeyword rejects type tokens that are actually keywords (so a
// `return x;` or `final` mis-parse never becomes a column).
func isDartFieldKeyword(t string) bool {
	switch t {
	case "return", "final", "const", "late", "var", "void", "if", "for",
		"while", "static", "get", "set":
		return true
	}
	return false
}

// indexBrace returns the byte offset of the first `{` in s (or 0 if none, so
// findBraceEndByte degrades gracefully).
func indexBrace(s string) int {
	if i := strings.IndexByte(s, '{'); i >= 0 {
		return i
	}
	return 0
}

// splitList splits a `[A, B, C]`-style inner list into trimmed identifiers.
func splitList(s string) []string {
	var out []string
	for _, p := range strings.Split(s, ",") {
		t := strings.TrimSpace(p)
		if t != "" {
			out = append(out, t)
		}
	}
	return out
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}
