/*
 * This file is generated by jOOQ codegen.
 */
package com.example.generated.jooq;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import com.example.generated.jooq.tables.Customer;
import com.example.generated.jooq.tables.Order;
import com.example.generated.jooq.tables.records.CustomerRecord;
import com.example.generated.jooq.tables.records.OrderRecord;

/**
 * A class modelling foreign key relationships between tables of the schema.
 */
public class Keys {

    // UNIQUE and PRIMARY KEY definitions
    public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_PRIMARY = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("KEY_CUSTOMER_PRIMARY"), new TableField[] { Customer.CUSTOMER.ID }, true);
    public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = Internal.createUniqueKey(Order.ORDER, DSL.name("KEY_ORDER_PRIMARY"), new TableField[] { Order.ORDER.ID }, true);

    // FOREIGN KEY definitions
    public static final ForeignKey<OrderRecord, CustomerRecord> FK_ORDER_CUSTOMER = Internal.createForeignKey(Order.ORDER, DSL.name("FK_ORDER_CUSTOMER"), new TableField[] { Order.ORDER.CUSTOMER_ID }, Keys.KEY_CUSTOMER_PRIMARY, new TableField[] { Customer.CUSTOMER.ID }, true);
    public static final ForeignKey<OrderRecord, CustomerRecord> FK_ORDER_SHIPPING_ADDRESS = Internal.createForeignKey(Order.ORDER, DSL.name("FK_ORDER_SHIPPING_ADDRESS"), new TableField[] { Order.ORDER.SHIPPING_ADDRESS_ID }, Keys.KEY_CUSTOMER_PRIMARY, new TableField[] { Customer.CUSTOMER.ID }, true);
}
