/*
 * This file is generated by jOOQ codegen.
 * See jooq-codegen.xml for configuration.
 */
package com.example.generated.jooq.tables;

import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.ForeignKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/**
 * Generated jOOQ Table class for the CUSTOMER table.
 */
public class Customer extends TableImpl<CustomerRecord> {

    public static final Customer CUSTOMER = new Customer();

    public final TableField<CustomerRecord, Long> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");
    public final TableField<CustomerRecord, String> FIRST_NAME = createField(DSL.name("FIRST_NAME"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");
    public final TableField<CustomerRecord, String> LAST_NAME = createField(DSL.name("LAST_NAME"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");
    public final TableField<CustomerRecord, String> EMAIL = createField(DSL.name("EMAIL"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Customer() {
        this(DSL.name("CUSTOMER"), null);
    }

    private Customer(Name alias, Table<CustomerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Customer(Name alias, Table<CustomerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    @Override
    public Class<CustomerRecord> getRecordType() {
        return CustomerRecord.class;
    }
}
