// CLAUDE.md / AGENTS.md pattern-block sync (ADR-0018 + gfleet upsert convention).
//
// Patterns are exported as a marker-wrapped block; user content outside
// the markers is preserved byte-for-byte. The block contains a short
// index (NOT the full pattern markdown — those live in
// docs/patterns/<category>/<id>.md) so a human scanning CLAUDE.md can
// click through to the canonical doc.
//
// Privacy: any AntiPattern with private=true is NEVER exported. This is
// the hard constraint from ADR-0018 — privacy boundary is the
// version-controlled file, not the in-memory query surface.
package agentpatterns

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

// Marker tokens used to wrap the pattern-block. v=1 lets future
// formats be auto-migrated without colliding with v=1 readers.
const (
	BlockStartMarker = "<!-- grafel:patterns:start v=1 -->"
	BlockEndMarker   = "<!-- grafel:patterns:end -->"
)

// blockRegex matches the entire marker-wrapped region including the
// markers themselves. Multiline + DOTALL semantics.
var blockRegex = regexp.MustCompile(`(?s)` +
	regexp.QuoteMeta(BlockStartMarker) +
	`.*?` +
	regexp.QuoteMeta(BlockEndMarker))

// ExportOptions tweak the rendered block.
type ExportOptions struct {
	// DocsRoot is the relative path from the CLAUDE.md file to the
	// generated pattern docs. Defaults to "docs/patterns".
	DocsRoot string
	// IncludeCandidates emits is_candidate=true patterns too. Default
	// false — only approved patterns end up in version control.
	IncludeCandidates bool
}

// RenderBlock builds the marker-wrapped block that will be written into
// CLAUDE.md. Skips candidates (unless opts.IncludeCandidates) and never
// emits private anti-patterns.
func RenderBlock(patterns []Pattern, opts ExportOptions) string {
	if opts.DocsRoot == "" {
		opts.DocsRoot = "docs/patterns"
	}

	// Filter + sort.
	exported := make([]Pattern, 0, len(patterns))
	for _, p := range patterns {
		if p.IsCandidate && !opts.IncludeCandidates {
			continue
		}
		exported = append(exported, p)
	}
	sort.Slice(exported, func(i, j int) bool {
		if exported[i].Category != exported[j].Category {
			return exported[i].Category < exported[j].Category
		}
		return exported[i].ID < exported[j].ID
	})

	var b strings.Builder
	fmt.Fprintln(&b, BlockStartMarker)
	fmt.Fprintln(&b)
	if len(exported) == 0 {
		fmt.Fprintln(&b, "_No approved patterns yet — run `/grafel-tech-docs` or `/grafel-patterns-discover` to bootstrap._")
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, BlockEndMarker)
		return b.String()
	}

	fmt.Fprintln(&b, "## Agent-learned patterns")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Generated by grafel. Do not edit between the markers — run `grafel patterns export` instead.")
	fmt.Fprintln(&b)

	var currentCategory Category
	for _, p := range exported {
		if p.Category != currentCategory {
			currentCategory = p.Category
			fmt.Fprintf(&b, "### %s\n\n", currentCategory)
		}
		// Each pattern: one-line trigger + link to the full doc.
		docPath := opts.DocsRoot + "/" + DocPathFor(p)
		fmt.Fprintf(&b, "- **%s** — confidence %.2f, %d observations. [Full recipe](%s)\n",
			oneLine(p.Trigger.NaturalLanguage), p.Confidence, p.Observations, docPath)
		// Inline anti-pattern callouts (public only).
		for _, ap := range p.AntiPatterns {
			if ap.Private {
				continue
			}
			fmt.Fprintf(&b, "  - Don't: %s (%s)\n", oneLine(ap.DoNot), oneLine(ap.Reason))
		}
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, BlockEndMarker)
	return b.String()
}

// UpsertFile reads path, replaces the marker block (or appends one if
// absent), and writes back atomically. Creates the file if missing.
// User content outside the markers is preserved byte-for-byte.
func UpsertFile(path string, patterns []Pattern, opts ExportOptions) error {
	block := RenderBlock(patterns, opts)
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", path, err)
	}
	var out []byte
	if os.IsNotExist(err) || len(existing) == 0 {
		out = []byte(block)
	} else if blockRegex.Match(existing) {
		out = blockRegex.ReplaceAll(existing, []byte(strings.TrimRight(block, "\n")))
	} else {
		// Append with a blank-line separator.
		buf := bytes.NewBuffer(existing)
		if len(existing) > 0 && existing[len(existing)-1] != '\n' {
			buf.WriteByte('\n')
		}
		buf.WriteByte('\n')
		buf.WriteString(block)
		out = buf.Bytes()
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, out, 0o644); err != nil {
		return fmt.Errorf("write tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("rename: %w", err)
	}
	return nil
}

// ExtractBlock returns the contents of the marker-wrapped block in path
// (excluding the markers themselves), or "" if no block exists.
func ExtractBlock(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	match := blockRegex.Find(data)
	if match == nil {
		return "", nil
	}
	inner := bytes.TrimPrefix(match, []byte(BlockStartMarker))
	inner = bytes.TrimSuffix(inner, []byte(BlockEndMarker))
	return strings.TrimSpace(string(inner)), nil
}

// ImportedRef is a pattern referenced by a CLAUDE.md block that the
// caller can then look up against the live pattern store.
type ImportedRef struct {
	TriggerLine string
	DocPath     string
}

// ParseBlock scans the marker block at path and returns the trigger
// summaries it contains. Used by /grafel-patterns-sync to surface
// "these patterns exist in CLAUDE.md but not in the store — import?".
func ParseBlock(path string) ([]ImportedRef, error) {
	inner, err := ExtractBlock(path)
	if err != nil {
		return nil, err
	}
	if inner == "" {
		return nil, nil
	}
	var refs []ImportedRef
	for _, line := range strings.Split(inner, "\n") {
		line = strings.TrimSpace(line)
		// We only care about lines that look like our pattern entries.
		// Format: `- **<trigger>** — confidence ... [Full recipe](docs/patterns/...)`
		if !strings.HasPrefix(line, "- **") {
			continue
		}
		trigger := extractBetween(line, "**", "**")
		docPath := extractBetween(line, "[Full recipe](", ")")
		if trigger != "" {
			refs = append(refs, ImportedRef{TriggerLine: trigger, DocPath: docPath})
		}
	}
	return refs, nil
}

// DiffReport summarises the result of comparing the pattern store against
// a CLAUDE.md block. Used by /grafel-patterns-sync.
type DiffReport struct {
	// InBlockOnly are trigger lines present in CLAUDE.md but missing
	// from the store.
	InBlockOnly []ImportedRef
	// InStoreOnly are patterns in the store but missing from the block
	// (would be added on next export).
	InStoreOnly []Pattern
}

// Diff compares the patterns slice (the store) against the marker block
// at path (the version-controlled file).
func Diff(path string, patterns []Pattern, opts ExportOptions) (DiffReport, error) {
	refs, err := ParseBlock(path)
	if err != nil {
		return DiffReport{}, err
	}

	storeTriggers := map[string]Pattern{}
	for _, p := range patterns {
		if p.IsCandidate && !opts.IncludeCandidates {
			continue
		}
		storeTriggers[oneLine(p.Trigger.NaturalLanguage)] = p
	}
	blockTriggers := map[string]ImportedRef{}
	for _, r := range refs {
		blockTriggers[r.TriggerLine] = r
	}

	var report DiffReport
	for _, ref := range refs {
		if _, ok := storeTriggers[ref.TriggerLine]; !ok {
			report.InBlockOnly = append(report.InBlockOnly, ref)
		}
	}
	for _, p := range patterns {
		if p.IsCandidate && !opts.IncludeCandidates {
			continue
		}
		if _, ok := blockTriggers[oneLine(p.Trigger.NaturalLanguage)]; !ok {
			report.InStoreOnly = append(report.InStoreOnly, p)
		}
	}
	return report, nil
}

// ---------------------------------------------------------------------------
// internal helpers
// ---------------------------------------------------------------------------

func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	return strings.TrimSpace(s)
}

func extractBetween(s, start, end string) string {
	i := strings.Index(s, start)
	if i < 0 {
		return ""
	}
	rest := s[i+len(start):]
	j := strings.Index(rest, end)
	if j < 0 {
		return ""
	}
	return rest[:j]
}
