package golang

import (
	"context"
	"regexp"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	"github.com/cajasmota/grafel/internal/extractor"
	"github.com/cajasmota/grafel/internal/types"
)

// gen (gorm.io/gen) is GORM's code generator. From GORM model structs it
// generates a typed, type-safe query API: a `Query` struct exposing one field
// per model (`q.User`), each backed by a generated query interface whose
// methods are the familiar GORM chain (`q.User.Where(...).Find()`). It also
// generates field helpers (`q.User.Name.Eq("x")`).
//
// gen wraps GORM models, so the model/field/relationship layer is GORM's (the
// gorm.go extractor owns the `gorm:"..."` tag surface). This extractor focuses
// on what gen *adds*: the generated typed-query API and the generator
// configuration that drives it.
//
// Mapping:
//   - `g := gen.NewGenerator(...)` / `g.ApplyBasic(model.User{})`   -> SCOPE.Schema (config)
//   - generated `type Query struct { User *user; ... }`             -> SCOPE.Schema (query API)
//   - `q.User.Where(...)` / `.Find()` / `.First()` typed query call -> SCOPE.Operation (query)
//   - GORM model structs referenced by ApplyBasic/ApplyInterface    -> SCOPE.Schema (model)
//
// Honesty: gen's own output models relationships only through the wrapped GORM
// tags (gorm.go territory) — gen adds no new relationship metadata — so
// Relationships is honesty-NA for gen specifically. Models is partial (the gen
// generator config + generated Query struct reveal the wrapped models, but the
// authoritative field/tag detail lives on the GORM structs). Queries is the
// strong capability: the typed `q.<Model>.<chainer>` surface attributes each
// query to a concrete model. Migrations is honesty-NA (gen generates query
// code, not migrations; GORM AutoMigrate/file migrations are gorm.go's).
func init() {
	extractor.Register("custom_go_gen", &genExtractor{})
}

type genExtractor struct{}

func (e *genExtractor) Language() string { return "custom_go_gen" }

var (
	// gen.NewGenerator(gen.Config{...}) — the generator entry point.
	reGenNewGenerator = regexp.MustCompile(`gen\.NewGenerator\(`)
	// g.ApplyBasic(model.User{}, model.Post{}) / g.ApplyInterface(...) — binds
	// the generator to concrete GORM models. We capture each model type.
	reGenApply = regexp.MustCompile(
		`(?m)\.(ApplyBasic|ApplyInterface)\(([^)]*)\)`,
	)
	// A model type reference inside an Apply call: model.User{} / User{} /
	// &model.User{} — capture the trailing type name.
	reGenModelRef = regexp.MustCompile(`&?(?:\w+\.)?(\w+)\{\}`)
	// g.GenerateModel("users") / g.GenerateModelAs("users", "User") generate a
	// model from a DB table name (introspection path).
	reGenGenerateModel = regexp.MustCompile(
		`(?m)\.(GenerateModel|GenerateModelAs|GenerateAllTable)\(`,
	)
	// The generated Query holder struct: `type Query struct { ... }` — present
	// in gen-generated files which carry a DO NOT EDIT header.
	reGenQueryStruct = regexp.MustCompile(
		`(?m)^//\s*Code generated by gorm\.io/gen\.\s*DO NOT EDIT\.`,
	)
	// Typed query call: q.User.Where(...) / Q.Post.First() — receiver.Model.Op.
	// The middle segment is the model; the trailing identifier is the chainer.
	reGenTypedQuery = regexp.MustCompile(
		`(?m)\b[qQ]\.(\w+)\.(Where|Order|Limit|Offset|Select|Joins|Preload|Group|Having|Find|First|Take|Last|Count|Create|CreateInBatches|Save|Update|Updates|Delete|Scan|FindInBatch)\(`,
	)
	// Field helper on a generated model: q.User.Name.Eq("x"). Recognised as a
	// query-time predicate builder.
	reGenFieldHelper = regexp.MustCompile(
		`(?m)\b[qQ]\.(\w+)\.(\w+)\.(Eq|Neq|Gt|Gte|Lt|Lte|Like|In|NotIn|Between)\(`,
	)
)

func (e *genExtractor) Extract(ctx context.Context, file extractor.FileInput) ([]types.EntityRecord, error) {
	tracer := otel.Tracer("grafel/custom/golang")
	_, span := tracer.Start(ctx, "indexer.gen_extractor.extract",
		trace.WithAttributes(
			attribute.String("language", file.Language),
			attribute.String("framework", "gen"),
			attribute.String("file_path", file.Path),
		),
	)
	defer span.End()

	if len(file.Content) == 0 || file.Language != "go" {
		return nil, nil
	}

	src := string(file.Content)
	var entities []types.EntityRecord
	seen := make(map[string]bool)
	add := func(ent types.EntityRecord) {
		key := ent.Kind + ":" + ent.Name
		if seen[key] {
			return
		}
		seen[key] = true
		entities = append(entities, ent)
	}

	// 1. Generator config: gen.NewGenerator(...) marks a gen generator program.
	for _, m := range reGenNewGenerator.FindAllStringSubmatchIndex(src, -1) {
		line := lineOf(src, m[0])
		ent := makeEntity("gen_generator", "SCOPE.Schema", "config", file.Path, file.Language, line)
		setProps(&ent, "framework", "gen", "provenance", "INFERRED_FROM_GEN_GENERATOR")
		add(ent)
	}

	// 2. ApplyBasic/ApplyInterface(model.X{}, ...) — the GORM models gen wraps.
	for _, m := range reGenApply.FindAllStringSubmatchIndex(src, -1) {
		method := submatch(src, m, 2)
		argList := submatch(src, m, 4)
		line := lineOf(src, m[0])
		for _, ref := range reGenModelRef.FindAllStringSubmatch(argList, -1) {
			model := ref[1]
			ent := makeEntity("model:"+model, "SCOPE.Schema", "", file.Path, file.Language, line)
			setProps(&ent, "framework", "gen", "provenance", "INFERRED_FROM_GEN_APPLY",
				"model_name", model, "apply_method", method)
			add(ent)
		}
	}

	// 3. GenerateModel("table") — DB-introspection model generation.
	for _, m := range reGenGenerateModel.FindAllStringSubmatchIndex(src, -1) {
		method := submatch(src, m, 2)
		line := lineOf(src, m[0])
		ent := makeEntity("gen_introspect:"+method, "SCOPE.Schema", "config", file.Path, file.Language, line)
		setProps(&ent, "framework", "gen", "provenance", "INFERRED_FROM_GEN_INTROSPECT",
			"generate_method", method)
		add(ent)
	}

	// 4. Generated Query holder struct (DO NOT EDIT header) marks generated code.
	for _, m := range reGenQueryStruct.FindAllStringSubmatchIndex(src, -1) {
		line := lineOf(src, m[0])
		ent := makeEntity("gen_query_api", "SCOPE.Schema", "query_api", file.Path, file.Language, line)
		setProps(&ent, "framework", "gen", "provenance", "INFERRED_FROM_GEN_GENERATED",
			"generated", "true")
		add(ent)
	}

	// 5. Typed query calls q.<Model>.<Op>(...) — attribute each to its model.
	for _, m := range reGenTypedQuery.FindAllStringSubmatchIndex(src, -1) {
		model := submatch(src, m, 2)
		op := submatch(src, m, 4)
		line := lineOf(src, m[0])
		ent := makeEntity("query:"+model+"."+op, "SCOPE.Operation", "query", file.Path, file.Language, line)
		setProps(&ent, "framework", "gen", "provenance", "INFERRED_FROM_GEN_TYPED_QUERY",
			"model_name", model, "query_op", op)
		add(ent)
	}

	// 5b. Field-level predicate helpers q.<Model>.<Field>.<Pred>(...).
	for _, m := range reGenFieldHelper.FindAllStringSubmatchIndex(src, -1) {
		model := submatch(src, m, 2)
		fieldH := submatch(src, m, 4)
		pred := submatch(src, m, 6)
		line := lineOf(src, m[0])
		ent := makeEntity("predicate:"+model+"."+fieldH+"."+pred, "SCOPE.Operation", "query", file.Path, file.Language, line)
		setProps(&ent, "framework", "gen", "provenance", "INFERRED_FROM_GEN_FIELD_HELPER",
			"model_name", model, "field_name", fieldH, "predicate", pred)
		add(ent)
	}

	span.SetAttributes(attribute.Int("entity_count", len(entities)))
	return entities, nil
}
