package golang

import (
	"context"
	"regexp"
	"strings"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	"github.com/cajasmota/grafel/internal/extractor"
	"github.com/cajasmota/grafel/internal/types"
)

// sqlc (github.com/sqlc-dev/sqlc) is a SQL-first code generator: you write
// plain SQL (schema + `-- name: X :one|:many|:exec` annotated queries) and a
// `sqlc.yaml` config, and sqlc emits a Go package (`models.go` with one struct
// per table, plus a query method per annotated statement). There is no
// hand-written ORM model layer — the generated code IS the model layer.
//
// This extractor reads BOTH sides honestly:
//   - the generated Go (`models.go` structs + generated query funcs that carry
//     a `// name: X :one` provenance comment and an embedded SQL const), and
//   - the source SQL (`-- name: X :one` annotated query files) and the
//     `sqlc.yaml` config that drives generation.
//
// Mapping:
//   - generated `type X struct { ... }` in a sqlc package -> SCOPE.Schema (model)
//   - generated struct field with a column comment        -> SCOPE.Component (field)
//   - `-- name: GetAuthor :one` query annotation          -> SCOPE.Operation (query)
//   - generated `func (q *Queries) GetAuthor(...)`        -> SCOPE.Operation (query)
//   - `sqlc.yaml` config (schema:/queries: paths)         -> SCOPE.Schema (config)
//   - associated NNN_slug.up/down.sql migration files     -> SCOPE.Schema (migration)
//
// Honesty: sqlc generates from SQL, so relationships/foreign keys are not
// modelled in the Go output at all (plain structs, no association metadata) —
// those capabilities are honesty-NA. Models/Queries/Migrations are detected
// from the generated-code + config + SQL-annotation patterns -> partial (a
// proving fixture exists for the annotated-query and config patterns).
func init() {
	extractor.Register("custom_go_sqlc", &sqlcExtractor{})
}

type sqlcExtractor struct{}

func (e *sqlcExtractor) Language() string { return "custom_go_sqlc" }

var (
	// sqlc stamps generated files with a header comment naming the version.
	//   // Code generated by sqlc. DO NOT EDIT.
	//   // versions:
	//   //   sqlc v1.25.0
	reSqlcGenHeader = regexp.MustCompile(
		`(?m)^//\s*Code generated by sqlc\.\s*DO NOT EDIT\.`,
	)
	// A generated model struct: `type Author struct { ... }`. We only treat
	// these as models when the file is a sqlc-generated file (header present).
	reSqlcStruct = regexp.MustCompile(
		"(?ms)type\\s+(\\w+)\\s+struct\\s*\\{(.*?)\\n\\}",
	)
	// A generated struct field line, e.g. `Name string` (optionally tagged).
	reSqlcField = regexp.MustCompile(
		"(?m)^\\s*(\\w+)\\s+([\\w\\.\\[\\]\\*]+)(?:\\s+`[^`]*`)?\\s*$",
	)
	// SQL query annotation comment: `-- name: GetAuthor :one`.
	// The verb (:one/:many/:exec/:execrows/:execresult/:batchexec/...) is the
	// sqlc result-kind directive.
	reSqlcQueryAnnot = regexp.MustCompile(
		`--\s*name:\s*(\w+)\s+:(\w+)`,
	)
	// Generated query method: `func (q *Queries) GetAuthor(ctx ...`. sqlc binds
	// every annotated query to a method on the *Queries receiver.
	reSqlcQueryFunc = regexp.MustCompile(
		`(?m)func\s+\(\s*q\s+\*Queries\s*\)\s+(\w+)\(`,
	)
	// sqlc.yaml config keys (version + schema/queries paths). Detecting the
	// config proves a sqlc project even when generated code is absent.
	reSqlcConfigSchema  = regexp.MustCompile(`(?m)^\s*schema:\s*`)
	reSqlcConfigQueries = regexp.MustCompile(`(?m)^\s*queries:\s*`)
	// File-based migrations associated with a sqlc project.
	reSqlcMigrationFile = regexp.MustCompile(
		`^(\d+)_([A-Za-z0-9_\-]+)\.(up|down)\.sql$`,
	)
)

func (e *sqlcExtractor) Extract(ctx context.Context, file extractor.FileInput) ([]types.EntityRecord, error) {
	tracer := otel.Tracer("grafel/custom/golang")
	_, span := tracer.Start(ctx, "indexer.sqlc_extractor.extract",
		trace.WithAttributes(
			attribute.String("language", file.Language),
			attribute.String("framework", "sqlc"),
			attribute.String("file_path", file.Path),
		),
	)
	defer span.End()

	if len(file.Content) == 0 {
		return nil, nil
	}

	src := string(file.Content)
	var entities []types.EntityRecord
	seen := make(map[string]bool)
	add := func(ent types.EntityRecord) {
		key := ent.Kind + ":" + ent.Name
		if seen[key] {
			return
		}
		seen[key] = true
		entities = append(entities, ent)
	}

	base := baseName(file.Path)

	// 1. File-based SQL migrations associated with a sqlc project.
	if m := reSqlcMigrationFile.FindStringSubmatch(base); m != nil {
		version, slug, direction := m[1], m[2], m[3]
		ent := makeEntity("migration:"+version+"_"+slug+"."+direction, "SCOPE.Schema", "migration", file.Path, file.Language, 1)
		setProps(&ent, "framework", "sqlc", "provenance", "INFERRED_FROM_SQLC_MIGRATION_FILE",
			"migration_version", version, "migration_slug", slug, "migration_direction", direction)
		add(ent)
		span.SetAttributes(attribute.Int("entity_count", len(entities)))
		return entities, nil
	}

	// 2. sqlc.yaml config: proves a sqlc project; record schema/queries dirs.
	if base == "sqlc.yaml" || base == "sqlc.yml" || base == "sqlc.json" {
		ent := makeEntity("sqlc_config:"+base, "SCOPE.Schema", "config", file.Path, file.Language, 1)
		setProps(&ent, "framework", "sqlc", "provenance", "INFERRED_FROM_SQLC_CONFIG",
			"has_schema", boolStr(reSqlcConfigSchema.MatchString(src)),
			"has_queries", boolStr(reSqlcConfigQueries.MatchString(src)))
		add(ent)
		span.SetAttributes(attribute.Int("entity_count", len(entities)))
		return entities, nil
	}

	// 3. SQL query annotations (`-- name: GetAuthor :one`) — the canonical sqlc
	//    query source. These appear in .sql files; we scan regardless of the
	//    declared language so a query file is detected by its annotation.
	for _, m := range reSqlcQueryAnnot.FindAllStringSubmatchIndex(src, -1) {
		name := submatch(src, m, 2)
		verb := submatch(src, m, 4)
		line := lineOf(src, m[0])
		ent := makeEntity("query:"+name, "SCOPE.Operation", "query", file.Path, file.Language, line)
		setProps(&ent, "framework", "sqlc", "provenance", "INFERRED_FROM_SQLC_ANNOTATION",
			"query_name", name, "result_kind", verb)
		add(ent)
	}

	if file.Language != "go" {
		span.SetAttributes(attribute.Int("entity_count", len(entities)))
		return entities, nil
	}

	// Generated-code patterns only apply to files sqlc itself produced.
	isGenerated := reSqlcGenHeader.MatchString(src)

	// 4. Generated query methods: func (q *Queries) GetAuthor(...). The method
	//    name is the sqlc query name; attribution is exact.
	for _, m := range reSqlcQueryFunc.FindAllStringSubmatchIndex(src, -1) {
		name := submatch(src, m, 2)
		line := lineOf(src, m[0])
		ent := makeEntity("query_func:"+name, "SCOPE.Operation", "query", file.Path, file.Language, line)
		setProps(&ent, "framework", "sqlc", "provenance", "INFERRED_FROM_SQLC_QUERY_FUNC",
			"query_name", name, "generated", boolStr(isGenerated))
		add(ent)
	}

	if !isGenerated {
		// Without the generated-code header we do not treat arbitrary structs as
		// sqlc models — that would over-claim. Query funcs above are specific
		// enough (the *Queries receiver) to stand alone.
		span.SetAttributes(attribute.Int("entity_count", len(entities)))
		return entities, nil
	}

	// 5. Generated model structs + their fields. In a sqlc-generated file every
	//    top-level struct is a table model; each field is a column.
	for _, sm := range reSqlcStruct.FindAllStringSubmatchIndex(src, -1) {
		structName := src[sm[2]:sm[3]]
		body := src[sm[4]:sm[5]]
		structLine := lineOf(src, sm[0])

		// Skip the Queries holder struct sqlc emits in db.go.
		if structName == "Queries" {
			continue
		}

		ent := makeEntity(structName, "SCOPE.Schema", "", file.Path, file.Language, structLine)
		setProps(&ent, "framework", "sqlc", "provenance", "INFERRED_FROM_SQLC_MODEL",
			"generated", "true")
		add(ent)

		for _, fm := range reSqlcField.FindAllStringSubmatch(body, -1) {
			fieldName := fm[1]
			fieldType := fm[2]
			fieldEnt := makeEntity("field:"+structName+"."+fieldName, "SCOPE.Component", "field", file.Path, file.Language, structLine)
			setProps(&fieldEnt, "framework", "sqlc", "provenance", "INFERRED_FROM_SQLC_FIELD",
				"model_name", structName, "field_name", fieldName,
				"column_name", sqlcColumnName(fieldName), "go_type", fieldType)
			add(fieldEnt)
		}
	}

	span.SetAttributes(attribute.Int("entity_count", len(entities)))
	return entities, nil
}

// sqlcColumnName converts sqlc's exported Go field name back to the snake_case
// column it was generated from. sqlc upper-camel-cases column names (and
// upper-cases known initialisms like ID); this is a best-effort inverse used
// for display.
func sqlcColumnName(field string) string {
	var b strings.Builder
	for i, r := range field {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// boolStr renders a bool as the string "true"/"false" for entity properties.
func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

// baseName returns the final path component of p, handling both / and \.
func baseName(p string) string {
	if i := strings.LastIndexAny(p, "/\\"); i >= 0 {
		return p[i+1:]
	}
	return p
}
