package golang

import (
	"context"
	"regexp"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	"github.com/cajasmota/grafel/internal/extractor"
	"github.com/cajasmota/grafel/internal/types"
)

// xo (github.com/xo/xo) is a database-first code generator: it introspects a
// live DB schema and emits Go types (one struct per table/view, with `db:` and
// `json:` tags), plus generated CRUD helpers (Insert/Update/Save/Delete) and
// generated lookup functions for indexes/foreign keys (e.g.
// `UserByID(ctx, db, id)` and `AuthorByID` from a FK). There is no
// hand-written schema DSL — the generated code is the model layer.
//
// Mapping:
//   - generated `type User struct { ... `db:"col"` ... }`        -> SCOPE.Schema (model)
//   - generated struct field with `db:"col"` tag                 -> SCOPE.Component (field)
//   - generated FK accessor `func (u *User) Author(...)`/         -> SCOPE.Component (relation)
//     `func AuthorByID(ctx, db, ...)`
//   - generated CRUD method `func (u *User) Insert(...)`/Update/  -> SCOPE.Operation (query)
//     Save/Upsert/Delete and `func UserByID(ctx, db, ...)`
//
// Honesty: xo derives FK relationships from the DB schema and emits accessor
// methods for them, so Relationships is detectable (partial — the FK accessor
// naming convention is a heuristic, not a declared association tag). Models &
// fields come from the generated `db:`-tagged structs (partial — recognised
// via the xo generated-code header + db tags). Queries come from the generated
// CRUD/by-index helper convention (partial). xo does not generate or manage
// migrations — it consumes an already-migrated schema — so Migrations is
// honesty-NA.
func init() {
	extractor.Register("custom_go_xo", &xoExtractor{})
}

type xoExtractor struct{}

func (e *xoExtractor) Language() string { return "custom_go_xo" }

var (
	// xo stamps generated files with a DO NOT EDIT header.
	//   // Code generated by xo. DO NOT EDIT.
	reXoGenHeader = regexp.MustCompile(
		`(?m)^//\s*Code generated by xo\.\s*DO NOT EDIT\.`,
	)
	// Generated struct: `type User struct { ... }`.
	reXoStruct = regexp.MustCompile(
		"(?ms)type\\s+(\\w+)\\s+struct\\s*\\{(.*?)\\n\\}",
	)
	// Generated field carrying a `db:"col"` tag (xo always tags columns).
	//   ID int `json:"id" db:"id"`
	reXoFieldTag = regexp.MustCompile(
		"(?m)^\\s*(\\w+)\\s+([\\w\\.\\[\\]\\*]+)\\s+`[^`]*db:\"([^\"]*)\"[^`]*`",
	)
	// Generated CRUD method on a model value: func (u *User) Insert(...).
	reXoCRUDMethod = regexp.MustCompile(
		`(?m)func\s+\(\s*\w+\s+\*(\w+)\s*\)\s+(Insert|Update|Save|Upsert|Delete|Replace)\(`,
	)
	// Generated lookup function from a unique index / primary key:
	//   func UserByID(ctx context.Context, db DB, id int) (*User, error)
	//   func UsersByName(ctx, db, name string) ([]*User, error)
	// Convention: <Type>By<Cols>. The leading type names the model; the suffix
	// is the index columns.
	reXoLookupFunc = regexp.MustCompile(
		`(?m)func\s+(\w+?)By(\w+)\(\s*ctx`,
	)
	// Generated FK accessor method: func (b *Book) Author(ctx, db) (*Author, error).
	// xo names the method after the referenced table. We detect a method whose
	// body returns a *OtherType, i.e. a single-word method on a pointer
	// receiver returning a pointer; heuristic via the signature.
	reXoFKAccessor = regexp.MustCompile(
		`(?m)func\s+\(\s*\w+\s+\*(\w+)\s*\)\s+(\w+)\(\s*ctx\s+context\.Context\s*,\s*db\s+\w+\s*\)\s*\(\s*\*(\w+)\s*,`,
	)
)

func (e *xoExtractor) Extract(ctx context.Context, file extractor.FileInput) ([]types.EntityRecord, error) {
	tracer := otel.Tracer("grafel/custom/golang")
	_, span := tracer.Start(ctx, "indexer.xo_extractor.extract",
		trace.WithAttributes(
			attribute.String("language", file.Language),
			attribute.String("framework", "xo"),
			attribute.String("file_path", file.Path),
		),
	)
	defer span.End()

	if len(file.Content) == 0 || file.Language != "go" {
		return nil, nil
	}

	src := string(file.Content)
	// xo's surface is only meaningful in generated files; the header guards
	// against treating arbitrary db-tagged structs (sqlx territory) as xo.
	if !reXoGenHeader.MatchString(src) {
		return nil, nil
	}

	var entities []types.EntityRecord
	seen := make(map[string]bool)
	add := func(ent types.EntityRecord) {
		key := ent.Kind + ":" + ent.Name
		if seen[key] {
			return
		}
		seen[key] = true
		entities = append(entities, ent)
	}

	// 1. Models + 2. fields from generated db-tagged structs.
	for _, sm := range reXoStruct.FindAllStringSubmatchIndex(src, -1) {
		structName := src[sm[2]:sm[3]]
		body := src[sm[4]:sm[5]]
		structLine := lineOf(src, sm[0])

		fields := reXoFieldTag.FindAllStringSubmatch(body, -1)
		if len(fields) == 0 {
			continue // not a column-bearing model struct
		}

		ent := makeEntity(structName, "SCOPE.Schema", "", file.Path, file.Language, structLine)
		setProps(&ent, "framework", "xo", "provenance", "INFERRED_FROM_XO_MODEL",
			"generated", "true")
		add(ent)

		for _, fm := range fields {
			fieldName := fm[1]
			fieldType := fm[2]
			column := fm[3]
			fieldEnt := makeEntity("field:"+structName+"."+fieldName, "SCOPE.Component", "field", file.Path, file.Language, structLine)
			setProps(&fieldEnt, "framework", "xo", "provenance", "INFERRED_FROM_XO_FIELD",
				"model_name", structName, "field_name", fieldName,
				"column_name", column, "go_type", fieldType)
			add(fieldEnt)
		}
	}

	// 3. FK accessor methods -> relationships. A method (recv *Model) returning
	//    (*Other, error) is xo's generated foreign-key navigation.
	for _, m := range reXoFKAccessor.FindAllStringSubmatchIndex(src, -1) {
		model := submatch(src, m, 2)
		method := submatch(src, m, 4)
		target := submatch(src, m, 6)
		line := lineOf(src, m[0])
		relEnt := makeEntity("rel:"+model+"."+method, "SCOPE.Component", "relation", file.Path, file.Language, line)
		setProps(&relEnt, "framework", "xo", "provenance", "INFERRED_FROM_XO_FK",
			"model_name", model, "accessor", method, "target_model", target,
			"relationship", "belongs_to")
		add(relEnt)
	}

	// 4a. CRUD methods -> query operations, attributed to the model.
	for _, m := range reXoCRUDMethod.FindAllStringSubmatchIndex(src, -1) {
		model := submatch(src, m, 2)
		op := submatch(src, m, 4)
		line := lineOf(src, m[0])
		ent := makeEntity("query:"+model+"."+op, "SCOPE.Operation", "query", file.Path, file.Language, line)
		setProps(&ent, "framework", "xo", "provenance", "INFERRED_FROM_XO_CRUD",
			"model_name", model, "query_op", op)
		add(ent)
	}

	// 4b. Generated <Type>By<Index> lookup functions -> query operations.
	for _, m := range reXoLookupFunc.FindAllStringSubmatchIndex(src, -1) {
		model := submatch(src, m, 2)
		index := submatch(src, m, 4)
		line := lineOf(src, m[0])
		ent := makeEntity("lookup:"+model+"By"+index, "SCOPE.Operation", "query", file.Path, file.Language, line)
		setProps(&ent, "framework", "xo", "provenance", "INFERRED_FROM_XO_LOOKUP",
			"model_name", model, "lookup_by", index)
		add(ent)
	}

	span.SetAttributes(attribute.Int("entity_count", len(entities)))
	return entities, nil
}
